### ISSUE TITLE
Assorted module issues from recent changes

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1161]
Edit: Updated quite a bit

I figure these relate to the replacement of the embedded module system with gestalt-module - little unsure whether the bug is here or if this should be in the gestalt-module tracker :-)
- [x] ~~Selecting a module where Core exists somewhere down the chain makes Core highlight yellow instead of green (gets selected as a dependency instead of mandatory module)~~ - should be worked via #689
- [x] ~~De-selecting a module where Core exists as a downstream dependency also de-selects Core~~ - should be worked via #689
- [x] ~~Disable all can disable Core (should be forced on, at least for now)~~ - should be worked via #689
- [ ] ~~Indirectly selected (yellow) modules appear unable to scan for / register world generators (like enabling Throughout the Ages 2 where the world gen is in 1)~~ - scan active module set (including dependencies) rather than only explicitly selected modules for world generators
- [x] ~~A module with module.info instead of module.txt (Rails) isn't showing up in the module list - unsure if that's because of the scanning or if Gradle tweaked to expect .info instead of .txt isn't building it right (has compiled classes though)~~ - will try to handle this via https://github.com/Nanoware/Terasology/issues/61
- [x] Module list is no longer alpha-sorted

Otherwise looks pretty stable, running my local integration workspace with all stable modules present!

Some of the fixes are probably easy but figuring best to leave for @immortius :-)
