### ISSUE TITLE
Various (crash) issues in Throughout the Ages

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1853]
Not all necessarily new or specific to v0.54.0 but thought I'd make a single issue for reference. I didn't dig particularly deep, just noted some initial, reported, or long-standing small issues that are particularly visible.

- [x] Planting a seed causes NPE - https://github.com/Terasology/WoodAndStone/issues/33
- [x] Using an herb bag causes crash - maybe dupe of the above item. Reference: #1734
- [x] Crash with seeds on hoed ground - likely again dupe or related to above two. #1725
- [x] Placing sapling causes NPE (1) (if reloading the world it did get placed, however)
- [x] Corn and rice are probably being delta prefabbed with a wrong asset name (2), unsure if they're even spawning (didn't spot any)
- [x] Scooping water into a bucket causes IndexOutOfBounds (3)
- [ ] Trees retain a sapling as the bottom block until looked at (old issue - https://github.com/Terasology/GrowingFlora/issues/2)

Poking @MarcinSc and @Josharias for possible fixes :-)

(1)

```
16:37:01.652 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.RuntimeException: component null
	at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:37) ~[classes/:na]
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:71) ~[classes/:na]
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:62) ~[classes/:na]
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:470) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:680) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:605) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:107) ~[classes/:na]
	at org.terasology.world.internal.EntityAwareWorldProvider.copyIntoPrefab(EntityAwareWorldProvider.java:292) ~[classes/:na]
	at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntityComponents(EntityAwareWorldProvider.java:282) ~[classes/:na]
	at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntity(EntityAwareWorldProvider.java:158) ~[classes/:na]
	at org.terasology.world.internal.EntityAwareWorldProvider.setBlock(EntityAwareWorldProvider.java:129) ~[classes/:na]
	at org.terasology.world.internal.WorldProviderWrapper.setBlock(WorldProviderWrapper.java:52) ~[classes/:na]
	at org.terasology.world.block.entity.placement.BlockPlacingSystem.placeBlockInWorld(BlockPlacingSystem.java:43) ~[classes/:na]
	at org.terasology.world.block.entity.placement.BlockPlacingSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.world.block.items.BlockItemSystem.onPlaceBlock(BlockItemSystem.java:100) ~[classes/:na]
	at org.terasology.world.block.items.BlockItemSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:139) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:192) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:157) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:338) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:174) ~[classes/:na]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:267) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:211) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:197) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:60) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:447) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
16:37:01.655 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

(2)

```
16:41:34.545 [Thread-5] WARN  o.t.a.module.ModuleAssetDataProducer - Discovered delta for unknown asset 'PlantPack:CornFruit'
16:41:34.549 [Thread-5] WARN  o.t.a.module.ModuleAssetDataProducer - Discovered delta for unknown asset 'PlantPack:RiceFruit'
```

(3)

```
16:43:31.264 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.terasology.fluid.system.FluidContainerAssetResolver.getAssetData(FluidContainerAssetResolver.java:97) ~[na:na]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType$$Lambda$46/127702987.run(Unknown Source) ~[na:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.fluid.system.FluidClientSystem.setFluidContainerIcon(FluidClientSystem.java:65) ~[na:na]
	at org.terasology.fluid.system.FluidClientSystem.onFluidContentsChanged(FluidClientSystem.java:47) ~[na:na]
	at org.terasology.fluid.system.FluidClientSystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:358) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.saveComponent(PojoEntityManager.java:651) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.saveComponent(BaseEntityRef.java:122) ~[classes/:na]
	at org.terasology.fluid.system.FluidUtils.setFluidForContainerItem(FluidUtils.java:30) ~[na:na]
	at org.terasology.fluid.system.FluidAuthoritySystem.fillFluidContainerItem(FluidAuthoritySystem.java:61) ~[na:na]
	at org.terasology.fluid.system.FluidAuthoritySystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:139) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:192) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:157) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:338) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:174) ~[classes/:na]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:267) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:211) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:197) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:60) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:447) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
16:43:31.269 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by immortius** [comment]
(1) happens because the SaplingInitializeSystem can remove the PlantedSaplingComponent during the processing of the OnAddedComponent event for that component, which messes up later events triggered from the adding the component (since it is gone). Doing some rough fixing of this (putting the notification for persistence system before the lifecycle events) still results in a crash though due to there being no plant definition for the new sapling.

**Comment by Cervator** [comment]
Linking to #1734 which may be an earlier report of one of these issues

**Comment by Cervator** [comment]
Found the CornFruit / RiceFruit issue. They used to live in PlantPack but were moved to AnotherWorldPlants yet WoodAndStone still had them in a deltas/PlantPack/... path

Also updated a bunch of assets that were still using . instead of # for atlas references. More working icon/items in TTA now!

**Comment by Cervator** [comment]
Closing as sufficiently fixed - no more crashes! At least none of the ones mentioned here.

Two survivors exist as issues

* https://github.com/Terasology/Fluid/issues/4
* https://github.com/Terasology/GrowingFlora/issues/2
