### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1975]
For the upcoming v1.0.0 release of the engine we should really overhaul our documentation to present a more comprehensive and consistent introduction to developing with the engine (and maybe playing the game in general). Need the help from multiple people here and new contributors can easily help by both pointing out weaknesses and figuring out then documenting simple things :-)

Big list of todos - not expecting we'll finish them all. Keep in mind a lot of these could be approached from two different contexts: how to code a new thing for feature x vs how to use feature x as a player
- [x] Game readme. Needs to be streamlined a lot, it is too bloated. A ton of it probably should be moved into the wiki (see #1974) and some other stuff into the few "magic" files like `CONTRIBUTING` (see #463). Mainly the readme should link to all kinds of stuff and show a brief into with a screenshot or two.
- [x] Hot keys. Currently in readme and on at least one outdated wiki page. Any good way to automatically scrape this from code? Or maybe just keep to the very basics (readme) - see #1470. Simple example on how to create a new hot key (or how to _avoid_ new keys in favor of better systems using existing functionality in-game) would be good as well. Maybe the Sample module should implement a custom hot key as a demo, showing a simple custom UI window? _Scraping for this implemented via #2051 - need to put to use_
- [x] Console commands. With the awesome in-game help system we have this in great shape. We probably just need to describe how to _develop_ for commands and delete any attempted lists of commands outside the game other than the very basics (again see #1470)
- [x] Put more hints into the launch scripts and the -help arguments about the launcher - see #1174
- [ ] Minimum requirements page - #1123
- [ ] Better organize + publish more intro videos to our gameplay templates like JoshariasSurvival or TTA (#932)
- [ ] The Sample module needs more stuff in it - #739
- [ ] Better introduction to using GitHub with the new tools available since we originally started, like the GitHub native client. We need a minimal hassle setup for contributors that don't necessarily need to code, such as artists just committing assets. #588
- [x] Slimmer version of the Dev Setup page in general, it too has bloated. Also a suggestion to have a basic overview video for those who follow visual instructions better (#217)
- [ ] Better doc + visibility for working on models / shapes in Blender. We have a nice forum thread at http://forum.terasology.org/threads/art-resources-guides-tutorial-videos-contributing-info.786 but again could use a nice short and sweet wiki page with details and links. #587 and maybe #508
- [ ] Review our code conventions, style guide, and add some basic tutorials for how to Javadoc and unit test (#135). Can link to existing guides for a generic intro, naturally, this is more to cover anything Terasology specific
- [ ] A world gen tutorial chapter on using biomes, which is an underutilized resource at present. #80 + https://github.com/Terasology/TutorialWorldGeneration/wiki + maybe overall review of the TutorialWorldGeneration repo and removal of "before 53.2" (assuming we have newer versions for everything covered)
- [ ] How to use the browser / html / widgets in our UI: https://github.com/MovingBlocks/Terasology/pull/1817#issuecomment-146887085
- [ ] Hook into any interesting external setups / add related doc. Example: http://yourfirstpr.github.io/ or https://github.com/todogroup/opencodeofconduct (more reading: http://www.erikaheidi.com/blog/is-your-open-source-project-welcoming-to-new-contributors)
- [ ] Better / clearer definitions of modules vs mods vs gameplay templates vs template + extras (related: #1911), how to actually make your own template from scratch (rather than just a plain module) including picking a default world gen etc
- [ ] Intro to our internationalization system (beyond its forum thread and Weblate)
- [ ] Intro to our options for AI. This could be a tricky one unless we manage to get the behavior tree system updated for v1.0.0. You can do AI differently though. Pathfinding overall is still somewhat of a weakness. Related: #1871, #1304 
- [x] Overhaul Modding API page. Maybe we can scrape something like all engine classes with @API ? Kinda sorta related to #862 if only by name (was that one issue part of what led to NovaAPI? Fun to think about)
- [x] Overhaul contributor wiki guide (#70 - oh hey, oldest open issue at this moment, and not even referring to the same wiki guide, heh, heh)
- [ ] Finally explain the "teams" in the forum, how to make progress, and what if any benefits are attached (like handing out @terasology.org forwards)
- [ ] Review and probably simplify the info tabs in the forum (sucks trying to keep them updated, should just be minimal with some links)
- [ ] Code conventions. See #2119. `@Generated` is another example and is used both for Protobuf in engine and somewhere in TeraMath where we should probably apply it as well
- [ ] Add a note about protobuf and what we need to do when it changes. See #2118
- [ ] Entity system module tutorial: #2153
- [ ] Asset tutorial: #2155
- [ ] Event tutorial: #2158
- [ ] Add annotations to API docs:  #2159

Related doc issues: https://github.com/MovingBlocks/Terasology/labels/Doc
##

**Comment by msteiger** [comment]
I added some documentation about [Fonts and Text](https://github.com/MovingBlocks/Terasology/wiki/Text-and-Font).

**Comment by Cervator** [comment]
Updated example of the ApiScraper in action after merging #2152:

# Modding API:

## terasology engine

* org.terasology.asset (PACKAGE)
* org.terasology.audio (PACKAGE)
* org.terasology.audio.events (PACKAGE)
* org.terasology.context.Context (INTERFACE)
* org.terasology.engine.ComponentFieldUri (CLASS)
* org.terasology.engine.Observer (INTERFACE)
* org.terasology.engine.SimpleUri (CLASS)
* org.terasology.engine.Time (INTERFACE)
* org.terasology.engine.Uri (INTERFACE)
* org.terasology.engine.bootstrap.ClassMetaLibrary (INTERFACE)
* org.terasology.engine.subsystem.common.ThreadManager (INTERFACE)
* org.terasology.engine.subsystem.common.hibernation.HibernationManager (CLASS)
* org.terasology.entitySystem (PACKAGE)
* org.terasology.entitySystem.entity (PACKAGE)
* org.terasology.entitySystem.entity.lifecycleEvents (PACKAGE)
* org.terasology.entitySystem.event (PACKAGE)
* org.terasology.entitySystem.prefab (PACKAGE)
* org.terasology.entitySystem.systems (PACKAGE)
* org.terasology.i18n.assets (PACKAGE)
* org.terasology.input (PACKAGE)
* org.terasology.input.binds.general (PACKAGE)
* org.terasology.input.binds.interaction (PACKAGE)
* org.terasology.input.binds.inventory (PACKAGE)
* org.terasology.input.binds.movement (PACKAGE)
* org.terasology.input.cameraTarget (PACKAGE)
* org.terasology.input.device.InputDevice (INTERFACE)
* org.terasology.input.device.KeyboardDevice (INTERFACE)
* org.terasology.input.device.MouseDevice (INTERFACE)
* org.terasology.input.events (PACKAGE)
* org.terasology.logic.actions (PACKAGE)
* org.terasology.logic.ai (PACKAGE)
* org.terasology.logic.autoCreate.AutoCreateComponent (CLASS)
* org.terasology.logic.behavior.BehaviorComponent (CLASS)
* org.terasology.logic.behavior.BehaviorNodeComponent (CLASS)
* org.terasology.logic.behavior.asset.BehaviorTree (CLASS)
* org.terasology.logic.behavior.nui (PACKAGE)
* org.terasology.logic.behavior.tree.Actor (CLASS)
* org.terasology.logic.behavior.tree.CompositeNode (CLASS)
* org.terasology.logic.behavior.tree.CounterNode (CLASS)
* org.terasology.logic.behavior.tree.DecoratorNode (CLASS)
* org.terasology.logic.behavior.tree.DecoratorNode$DecoratorTask (CLASS)
* org.terasology.logic.behavior.tree.Interpreter (CLASS)
* org.terasology.logic.behavior.tree.MonitorNode (CLASS)
* org.terasology.logic.behavior.tree.Node (CLASS)
* org.terasology.logic.behavior.tree.ParallelNode (CLASS)
* org.terasology.logic.behavior.tree.RepeatNode (CLASS)
* org.terasology.logic.behavior.tree.SelectorNode (CLASS)
* org.terasology.logic.behavior.tree.SequenceNode (CLASS)
* org.terasology.logic.behavior.tree.SetAnimationNode (CLASS)
* org.terasology.logic.behavior.tree.Status (CLASS)
* org.terasology.logic.behavior.tree.Task (CLASS)
* org.terasology.logic.characters (PACKAGE)
* org.terasology.logic.characters.events (PACKAGE)
* org.terasology.logic.characters.interactions.InteractionEndPredicted (CLASS)
* org.terasology.logic.characters.interactions.InteractionStartPredicted (CLASS)
* org.terasology.logic.characters.interactions.InteractionUtil (CLASS)
* org.terasology.logic.chat (PACKAGE)
* org.terasology.logic.clipboard.ClipboardManager (INTERFACE)
* org.terasology.logic.common (PACKAGE)
* org.terasology.logic.common.lifespan (PACKAGE)
* org.terasology.logic.config.ModuleConfigManager (INTERFACE)
* org.terasology.logic.console (PACKAGE)
* org.terasology.logic.console.commandSystem.CommandParameterSuggester (INTERFACE)
* org.terasology.logic.console.commandSystem.ConsoleCommand (INTERFACE)
* org.terasology.logic.console.commandSystem.adapter.ParameterAdapter (INTERFACE)
* org.terasology.logic.console.commandSystem.adapter.ParameterAdapterManager (CLASS)
* org.terasology.logic.console.commandSystem.annotations (PACKAGE)
* org.terasology.logic.console.suggesters (PACKAGE)
* org.terasology.logic.debug.DebugPropertiesSystem (CLASS)
* org.terasology.logic.delay (PACKAGE)
* org.terasology.logic.health (PACKAGE)
* org.terasology.logic.inventory (PACKAGE)
* org.terasology.logic.inventory.action.GiveItemAction (CLASS)
* org.terasology.logic.inventory.action.MoveItemAction (CLASS)
* org.terasology.logic.inventory.action.RemoveItemAction (CLASS)
* org.terasology.logic.inventory.action.SwitchItemAction (CLASS)
* org.terasology.logic.inventory.events (PACKAGE)
* org.terasology.logic.location (PACKAGE)
* org.terasology.logic.nameTags.NameTagComponent (CLASS)
* org.terasology.logic.particles (PACKAGE)
* org.terasology.logic.players (PACKAGE)
* org.terasology.logic.players.event (PACKAGE)
* org.terasology.logic.selection.ApplyBlockSelectionEvent (CLASS)
* org.terasology.logic.spawner (PACKAGE)
* org.terasology.math (PACKAGE)
* org.terasology.monitoring (PACKAGE)
* org.terasology.network (PACKAGE)
* org.terasology.network.events (PACKAGE)
* org.terasology.persistence.TemplateEngine (INTERFACE)
* org.terasology.persistence.TemplateEngineImpl (CLASS)
* org.terasology.persistence.typeHandling (PACKAGE)
* org.terasology.persistence.typeHandling.RegisterTypeHandler (INTERFACE)
* org.terasology.physics (PACKAGE)
* org.terasology.physics.components (PACKAGE)
* org.terasology.physics.events (PACKAGE)
* org.terasology.physics.shapes (PACKAGE)
* org.terasology.reflection.MappedContainer (INTERFACE)
* org.terasology.registry (PACKAGE)
* org.terasology.rendering.FontColor (CLASS)
* org.terasology.rendering.FontUnderline (CLASS)
* org.terasology.rendering.assets.animation (PACKAGE)
* org.terasology.rendering.assets.font (PACKAGE)
* org.terasology.rendering.assets.material (PACKAGE)
* org.terasology.rendering.assets.mesh (PACKAGE)
* org.terasology.rendering.assets.mesh.MeshBuilder$TextureMapper (INTERFACE)
* org.terasology.rendering.assets.shader (PACKAGE)
* org.terasology.rendering.assets.skeletalmesh (PACKAGE)
* org.terasology.rendering.assets.texture (PACKAGE)
* org.terasology.rendering.assets.texture.subtexture (PACKAGE)
* org.terasology.rendering.cameras (PACKAGE)
* org.terasology.rendering.iconmesh.IconMeshFactory (CLASS)
* org.terasology.rendering.logic (PACKAGE)
* org.terasology.rendering.nui (PACKAGE)
* org.terasology.rendering.nui.Color (CLASS)
* org.terasology.rendering.nui.ScreenLayerClosedEvent (CLASS)
* org.terasology.rendering.nui.asset.UIData (CLASS)
* org.terasology.rendering.nui.asset.UIElement (CLASS)
* org.terasology.rendering.nui.databinding (PACKAGE)
* org.terasology.rendering.nui.events (PACKAGE)
* org.terasology.rendering.nui.itemRendering (PACKAGE)
* org.terasology.rendering.nui.layers.hud (PACKAGE)
* org.terasology.rendering.nui.layers.ingame (PACKAGE)
* org.terasology.rendering.nui.layers.ingame.inventory (PACKAGE)
* org.terasology.rendering.nui.layouts (PACKAGE)
* org.terasology.rendering.nui.layouts.miglayout (PACKAGE)
* org.terasology.rendering.nui.layouts.relative (PACKAGE)
* org.terasology.rendering.nui.properties (PACKAGE)
* org.terasology.rendering.nui.properties.Checkbox (INTERFACE)
* org.terasology.rendering.nui.properties.OneOf (INTERFACE)
* org.terasology.rendering.nui.properties.OneOf$Enum (INTERFACE)
* org.terasology.rendering.nui.properties.OneOf$List (INTERFACE)
* org.terasology.rendering.nui.properties.OneOf$Provider (INTERFACE)
* org.terasology.rendering.nui.properties.OneOfProviderFactory (CLASS)
* org.terasology.rendering.nui.properties.Range (INTERFACE)
* org.terasology.rendering.nui.properties.TextField (INTERFACE)
* org.terasology.rendering.nui.skin (PACKAGE)
* org.terasology.rendering.nui.widgets (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data.basic (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data.basic.flow (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data.html (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data.html.basic (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.data.html.basic.list (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.ui (PACKAGE)
* org.terasology.rendering.nui.widgets.browser.ui.style (PACKAGE)
* org.terasology.rendering.primitives.BlockMeshGenerator (INTERFACE)
* org.terasology.rendering.primitives.Tessellator (CLASS)
* org.terasology.rendering.primitives.TessellatorHelper (CLASS)
* org.terasology.rendering.world.selection.BlockSelectionRenderer (CLASS)
* org.terasology.utilities.OrdinalIndicator (CLASS)
* org.terasology.utilities.collection (PACKAGE)
* org.terasology.utilities.concurrency (PACKAGE)
* org.terasology.utilities.procedural (PACKAGE)
* org.terasology.utilities.random.FastRandom (CLASS)
* org.terasology.utilities.random.MersenneRandom (CLASS)
* org.terasology.utilities.random.Random (CLASS)
* org.terasology.world (PACKAGE)
* org.terasology.world.biomes.Biome (INTERFACE)
* org.terasology.world.biomes.BiomeRegistrator (INTERFACE)
* org.terasology.world.biomes.BiomeRegistry (INTERFACE)
* org.terasology.world.block (PACKAGE)
* org.terasology.world.block.entity (PACKAGE)
* org.terasology.world.block.entity.damage (PACKAGE)
* org.terasology.world.block.entity.neighbourUpdate (PACKAGE)
* org.terasology.world.block.entity.placement (PACKAGE)
* org.terasology.world.block.family (PACKAGE)
* org.terasology.world.block.items (PACKAGE)
* org.terasology.world.block.loader.BlockFamilyDefinition (CLASS)
* org.terasology.world.block.loader.BlockFamilyDefinitionData (CLASS)
* org.terasology.world.block.loader.EntityData (CLASS)
* org.terasology.world.block.loader.InventoryData (CLASS)
* org.terasology.world.block.loader.SectionDefinitionData (CLASS)
* org.terasology.world.block.regions (PACKAGE)
* org.terasology.world.block.shapes (PACKAGE)
* org.terasology.world.block.tiles.WorldAtlas (INTERFACE)
* org.terasology.world.block.typeEntity (PACKAGE)
* org.terasology.world.chunks.Chunk (INTERFACE)
* org.terasology.world.chunks.ChunkBlockIterator (INTERFACE)
* org.terasology.world.chunks.ChunkConstants (CLASS)
* org.terasology.world.chunks.CoreChunk (INTERFACE)
* org.terasology.world.chunks.LitChunk (INTERFACE)
* org.terasology.world.chunks.ManagedChunk (INTERFACE)
* org.terasology.world.chunks.RenderableChunk (INTERFACE)
* org.terasology.world.chunks.event (PACKAGE)
* org.terasology.world.generation (PACKAGE)
* org.terasology.world.generation.facets (PACKAGE)
* org.terasology.world.generation.facets.base (PACKAGE)
* org.terasology.world.generator (PACKAGE)
* org.terasology.world.generator.plugin (PACKAGE)
* org.terasology.world.liquid.LiquidData (CLASS)
* org.terasology.world.liquid.LiquidType (CLASS)
* org.terasology.world.selection.BlockSelectionComponent (CLASS)
* org.terasology.world.selection.event (PACKAGE)
* org.terasology.world.sun (PACKAGE)
* org.terasology.world.time (PACKAGE)
* org.terasology.world.viewer.color (PACKAGE)
* org.terasology.world.viewer.layers (PACKAGE)
* org.terasology.world.viewer.layers.FacetLayerConfig (INTERFACE)
* org.terasology.world.viewer.layers.engine (PACKAGE)
* org.terasology.world.viewer.picker (PACKAGE)

## external

* com.bulletphysics.linearmath (PACKAGE)
* com.esotericsoftware.reflectasm.MethodAccess (CLASS)
* com.google.common.annotations (PACKAGE)
* com.google.common.base (PACKAGE)
* com.google.common.cache (PACKAGE)
* com.google.common.collect (PACKAGE)
* com.google.common.math (PACKAGE)
* com.google.common.primitives (PACKAGE)
* com.google.common.util.concurrent (PACKAGE)
* com.yourkit.runtime (PACKAGE)
* gnu.trove (PACKAGE)
* gnu.trove.decorator (PACKAGE)
* gnu.trove.function (PACKAGE)
* gnu.trove.iterator (PACKAGE)
* gnu.trove.iterator.hash (PACKAGE)
* gnu.trove.list (PACKAGE)
* gnu.trove.list.array (PACKAGE)
* gnu.trove.list.linked (PACKAGE)
* gnu.trove.map (PACKAGE)
* gnu.trove.map.custom_hash (PACKAGE)
* gnu.trove.map.hash (PACKAGE)
* gnu.trove.procedure (PACKAGE)
* gnu.trove.procedure.array (PACKAGE)
* gnu.trove.queue (PACKAGE)
* gnu.trove.set (PACKAGE)
* gnu.trove.set.hash (PACKAGE)
* gnu.trove.stack (PACKAGE)
* gnu.trove.stack.array (PACKAGE)
* gnu.trove.strategy (PACKAGE)
* java.awt (PACKAGE)
* java.awt.datatransfer.UnsupportedFlavorException (CLASS)
* java.awt.geom (PACKAGE)
* java.awt.image (PACKAGE)
* java.io.BufferedReader (CLASS)
* java.io.IOException (CLASS)
* java.io.Reader (CLASS)
* java.io.StringReader (CLASS)
* java.lang (PACKAGE)
* java.lang.invoke (PACKAGE)
* java.lang.ref (PACKAGE)
* java.lang.reflect.InvocationTargetException (CLASS)
* java.math (PACKAGE)
* java.nio.ByteBuffer (CLASS)
* java.nio.IntBuffer (CLASS)
* java.util (PACKAGE)
* java.util.concurrent (PACKAGE)
* java.util.concurrent.atomic (PACKAGE)
* java.util.concurrent.locks (PACKAGE)
* java.util.function (PACKAGE)
* java.util.regex (PACKAGE)
* java.util.stream (PACKAGE)
* javax.vecmath (PACKAGE)
* org.slf4j.Logger (CLASS)
* org.slf4j.LoggerFactory (CLASS)
* org.terasology.math.geom (PACKAGE)
* org.terasology.world.biomes (PACKAGE)
* sun.reflect (PACKAGE)

## gestalt-module

* org.terasology.naming (PACKAGE)
* org.terasology.naming.exception (PACKAGE)

## gestalt-asset-core

* org.terasology.assets.AbstractFragmentDataProducer (CLASS)
* org.terasology.assets.Asset (CLASS)
* org.terasology.assets.AssetData (INTERFACE)
* org.terasology.assets.AssetDataProducer (INTERFACE)
* org.terasology.assets.AssetFactory (INTERFACE)
* org.terasology.assets.AssetType (CLASS)
* org.terasology.assets.ResourceUrn (CLASS)
* org.terasology.assets.exceptions (PACKAGE)
* org.terasology.assets.format (PACKAGE)
* org.terasology.assets.management.AssetManager (CLASS)
* org.terasology.assets.module.annotations (PACKAGE)
* org.terasology.assets.module.annotations.RegisterAssetDataProducer (INTERFACE)
* org.terasology.assets.module.annotations.RegisterAssetDeltaFileFormat (INTERFACE)
* org.terasology.assets.module.annotations.RegisterAssetFileFormat (INTERFACE)
* org.terasology.assets.module.annotations.RegisterAssetSupplementalFileFormat (INTERFACE)
* org.terasology.assets.module.annotations.RegisterAssetType (INTERFACE)

**Comment by rajiv-thorat** [comment]
Fixing some errors found in JavaDocs.

**Comment by Cervator** [comment]
I've gone over the main list here and split out one issue, everything else still outstanding either already has issues, is obsolete, or not really very important to where we'll need this open (odds are we'll catch it as part of general improvements. So I'm closing this as sufficiently complete to get it out of the way
