### ISSUE TITLE
Physics-based combat system (resurrect old system?) [$100]

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2072]
We had a near-complete combat system done by @aherber back in the legacy days based on a physics model. While we can currently simulate combat by just triggering damage events while two entities are near each other that's pretty boring. 

The legacy system had a bow that would shoot different types of arrows including one affected by gravity, one that would bounce off surfaces, etc. It also had a sword for simple melee combat if you were faced with a target you could hit. The next step was enabling positional damage, opening the door to headshots, limb-specific damage, equipment mattering a whole lot more, and whole related systems like armor and health that could be more than just a global pool of points.

Whether we can resurrect the old system or not we need fancier combat!
- @nh-99 made the last attempt to look at it and got it into a branch here in this repo. Note that it is a single commit not isolating the changes, but it should work and somebody should be able to identify the related code and see if it is useful anymore: https://github.com/MovingBlocks/Terasology/tree/combat_archive
- Forum thread: http://forum.terasology.org/threads/combat.420 - lots of details, including near the end a note about @nh-99's work
- Some other basic notes about a simpler system (and old alternative combat) in #603. May not work anymore either.

Somewhat like the Behavior Tree overhaul (#2070) I'm expecting a basic scope here to claim the bounty with lots of bonus potential running into GSOC scale land.

**Basic implementation**
- [ ] Either resurrect the old branch or use it for inspiration to develop a new physics-based combat system. Or surprise us with something clever that gets to the same level of gameplay (more than just mashing buttons in melee hoping you're hitting something). Not expecting _where_ a target is hit to matter here.
- [ ] Make a basic projectile weapon that could satisfy #2570 - could be a stepping stone, may not need full physics (more like a tweaked railgun)
- [ ] Probably will need to touch on pathfinding or BTs to actually have creatures engage in combat. There are alternative options for AI though
- [ ] Implement an aggressive (test) mob that'll use the system with some level of competency (if a player or other suitable target is in range point at it and start shooting it with arrows or what not)
- [ ] Allow the player to use the new system as well and aim attacks sensibly. Ideally show a few different projectile types like the old system
- [ ] Verify that it all works in multiplayer without atrocious latency :-)
- [ ] Add/review javadoc for all involved classes
- [ ] Add tutorial about how to work/extend the system and any involved items, again ideally in the style of https://github.com/Terasology/TutorialWorldGeneration/
- [ ] Make a showcase video

**Advanced implementation**

This is far more open-ended and leads into creating/updating related systems
- [ ] Improve the display of health and especially the impact from losing/gaining health (combat/healing) - #1639
- [ ] Make some basic potions that relate to combat. Healing potions, poisons you can apply to a weapon, other weapon enhancement effects (flaming projectiles? A trueshot position making your aim better?) - #737
- [ ] Implement positional damage. Headshots should hurt more than toeshots. This would then also involve actually defining what's a head and what's a toe.
- [ ] Implement an anatomy system that can take the impact from positional damage and give it gameplay value. Could also lead into non-combat factors like hunger, disease, falling, etc. #465
- [ ] Make a projectile that can _stick_ to something, be that a wall, a player, or something else. Could also be used for utility like sticky torches - #1443
- [ ] Make a turret-based weapon that can track specified targets and fire projectiles at them within a certain range and constraints (no firing through walls). Think a guard tower with a balista of some sort. May also relate to #664, #591, #589, #581

This issue obsoletes #590 - figured I'd create a new one to get it fully up to speed.
##

**Comment by 0shine0** [comment]
Pinging @Cervator to discuss its potential in Gsoc and also about its implementation.

I am thinking about using the useful parts from the old branch to facilitate a new combat system. Should I make the system in a new module or make it in core module?

**Comment by portokaliu** [comment]
Scavenging bits of the old system was always an idea, since the functionality seemed to be there. The only issue was that it used a really old version of the game and rooted itself in some core/engine classes, when it would most likely need to be a module.

**Comment by 0shine0** [comment]
@portokaliu I am also thinking about introducing a density property for non-solid materials like water. To affect speed and motion of a projectile in water as compared to when in air.

**Comment by portokaliu** [comment]
@0shine0 This was one of the ideas for the movement refactoring, but that only referred to the player. Suffice to say, I'm not against that concept

**Comment by 0shine0** [comment]
@portokaliu alright, gonna try that with combat system.

**Comment by Cervator** [comment]
Closing this as completed as part of GSOC 2017, woo! New module https://github.com/Terasology/CombatSystem is the primary home for the new system, and has some sibling modules :-)

Thanks @0shine0 and mentors @portokaliu @niksoc @xrtariq2594 !

As usual there are plenty of additional areas that could still be worked on, maybe especially positional combat / damage, but that is for another day :-)

For a summary of work done see https://gist.github.com/0shine0/aba355bbc437b57b3c5d8aaeaa2a0296

Also, somebody should claim the bounty on top :D
