### ISSUE TITLE
Improve progress reporting when retrieving modules from a server

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2230]
This is closely related to #1626 but split out as a pure contributor friendly UI issue. Still, might be doable to do both at once. If done solo at least it should make the other issue easier to deal with.

At present if you connect to a server and there is a mismatch between versions the client is supposed to be sent the server version of the conflicting modules. In some cases this breaks and just shows:

![terasology _ alpha_2016-03-13_15-30-13](https://cloud.githubusercontent.com/assets/1063833/13732499/9624c090-e95a-11e5-80a8-cfa2f1709d79.png)

Nothing gets logged, no updates are pushed to the UI, it just stalls, no way to cancel. Possible improvements:

- [ ] Fix #1626 (naturally, but optional)
- [ ] Actually log some info statements about what module is actively being downloaded
- [ ] Clarify the progress reporting with what is being downloaded at what version
- [ ] Add a counter for how many modules have been downloaded / are needed
- [ ] Add a timeout so the game will eventually give up if it takes too long to download (may be more relevant to fix under #1626)
- [ ] Add a cancel button on the world loading screen that can be used in any case / at any time to terminate game loading and return to the main menu (so not really related directly to #1626)

This may be tricky to test without fixing #1626 but scenarios have been encountered where it works fine. Maybe run a server with modules and a client *without* modules so they're just missing rather than conflicting in version level.
