### ISSUE TITLE
NUI Extraction

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2307]
### Contains

A list of dependencies that need to be resolved in order to extract NUI ([org.terasology.rendering.nui](https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/java/org/terasology/rendering/nui)) into a standalone library: [MovingBlocks/TeraNUI](https://github.com/MovingBlocks/TeraNUI). These can generally be resolved individually.
- [ ] CoreRegistry is utilised by [UIFormat](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java), [UISkinFormat](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java) and [PropertyProvider](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/properties/PropertyProvider.java). However, since the extracted library shouldn't have a Context dependency, a different way of doing dependency injection will need to be introduced here (passing constructor parameters, for instance). Refer to #1818 for some relevant discussion.
- [ ] NUI depends heavily on [org.terasology.input](https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/java/org/terasology/input), which in turn depends on [org.terasology.entitySystem](https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/java/org/terasology/entitySystem). This package is currently being refactored into a gestalt library, but NUI is not expected to depend on it - a new way of handling entities will need to be developed instead.
- [ ] [org.terasology.input.BindableButton](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/input/BindableButton.java) uses a [SimpleUri](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/SimpleUri.java) as an identifier - since this class is essentially a wrapper around a gestalt-asset-core Uri string, it can potentially be moved to gestalt.
- [ ] [org.terasology.rendering.nui.skin.UIStyle](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/skin/UIStyle.java) depends on [org.terasology.math.Border](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/math/Border.java). This can be resolved by moving the class (and, potentially, other parts of the math package?) to [MovingBlocks/TeraMath](https://github.com/MovingBlocks/TeraMath).
- [ ] [org.terasology.rendering.nui.databinding.BindHelper](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/databinding/BindHelper.java) uses [ReflectionUtil](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/utilities/ReflectionUtil.java). The only non-common dependency this class has is NUI itself, but it is used in packages other than NUI - resolving this might be tricky. (**16.01.2017 EDIT:** [InjectionHelper](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/registry/InjectionHelper.java) - the reflection magic helper handling stuff such as `@In` and `@Share` - might be a nice addition to an extracted NUI)
- [ ] The [UIText](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java) widget uses [org.terasology.rendering.FontColor](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/FontColor.java) and [org.terasology.rendering.FontUnderline](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/FontUnderline.java). Note that this only needs to be resolved if the widgets are considered common classes that should be extracted.
- [ ] One particularly hard-to-extract class [UIFormat](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java) - in addition to the previously mentioned CoreRegisty, it depends on a large amount of Terasology packages:
  - org.terasology.i18n.TranslationSystem
  - org.terasology.persistence.\* 
  - org.terasology.reflection.metadata.ClassMetadata
  - org.terasology.utilities.ReflectionUtil
  - org.terasology.utilities.gson.CaseInsensitiveEnumTypeAdapterFactory

Any other dependencies that need to be resolved will be added as they are found.
Potentially relevant to @msteiger, @flo, @immortius.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33696963-nui-extraction?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).

**Comment by flo** [comment]
thanks for gathering the points and putting them into an issue.

**Comment by Cervator** [comment]
Slight bump just to link http://forum.terasology.org/threads/config-context-and-security.1761 to this issue. Also to mention gestalt-entity is somewhat extracted at this point and there's interest in NUI maybe being reviewed for use in DestSol one day.

**Comment by BenjaminAmos** [comment]
I've done some work on analysing the dependencies that need to be resolved. The actual data on this can be found [here](https://gist.github.com/BenjaminAmos/846005f427b54bb0b36b30a5073ebca2) but in summary I think (in my opinion) that the following dependencies will need to be resolved (I have also left some suggestions about where to move the classes to):

### Terasology-only packages (these packages should not be ported and NUI depedencies on these should be removed):
 - org.terasology.rendering.nui.layers (contains Terasology's main menu and HUD)
 - org.terasology.rendering.nui.editor (contains Terasology's NUI editor)
 - org.terasology.persistence (contains Terasology's serialisation system, which NUI's functionality should not depend on)
 - org.terasology.registry (contains Terasology's Context and CoreRegistry systems, which are not part of NUI's functionality)
 - org.terasology.rendering.assets.mesh - NUI does not use meshes as part of the UI
 - org.terasology.rendering.assets.material - NUI does not use materials as part of the UI (it uses UISkin instead)

### Terasology-only classes:
 - org.terasology.rendering.nui.SortOrderSystem - depends on gestalt-entity-system
 - org.terasology.rendering.nui.NUIManager - depends on gestalt-entity-system
 - org.terasology.rendering.nui.ScreenLayerClosedEvent - depends on gestalt-entity-system
 - org.terasology.rendering.nui.BaseInteractionScreen - depends on gestalt-entity-system
 - org.terasology.il8n.TranslationSystem (this is used to translate UI strings) - only used by a few NUI widgets
 - org.terasology.input.BindableButton - this class provides the same functionality as NUI's input classes
 - org.terasology.input.BindButtonEvent - relates to BindableButton
 - org.terasology.input.BindButtonSubscriber - relates to BindableButton
 - org.terasology.input.binds.general.TabbingUIButton - relates to BindableButton

### Common shared packages (these should be extracted into a common place for use in both NUI and Terasology):
 - org.terasology.reflection (used in org.terasology.rendering.nui.properties.PropertyProvider) - extract into seperate library
 - org.terasology.input (excluding entity-system events/systems/components) - extract into seperate library

### Common shared classes:
 - org.terasology.rendering.nui.Color - extract with NUI
 - org.terasology.utilities.ReflectionUtil - extract with org.terasology.reflection
 - org.terasology.rendering.assets.font.Font - extract with NUI
 - org.terasology.rendering.assets.texture.TextureRegion - extract with NUI

### Useful packages (these packages are part of Terasology and are not needed in NUI, however they might be useful with it):
 - org.terasology.rendering.nui.internal - most of the files here are heavily dependant on Terasology, yet could be useful if extracted as part of NUI (especially the CanvasImpl class)
 - org.terasology.rendering.nui.animation (contains Terasology's animation system, although this could be extracted) - possibly extract with NUI

### Valid External dependencies (these dependencies are used by NUI directly):
 - com.google.code.gson (JSON serialiser)
 - org.slf4f (logging)
 - guava (Java utilities, transistive dependency from gestalt)
 - gestalt-module (module assets and @API annotations)
 - gestalt-asset-core (assets)
 - net.sf.trove4j (optimised collections)

### Invalid External dependencies (these dependencies are used by NUI but should be removed):
 - org.lwjgl.lwjgl - NUI should not be dependant on a specific rendering back-end (the classes using this directly could be put into a nui-lwjgl library though)

**Comment by Cervator** [comment]
Been a long time coming (/wave @rzats) but this is about to be completed by #4017 / fixed by #4017 thanks to a bunch of solid contributors 👍

**Comment by Cervator** [comment]
Closing as completed by #4017 and many friends in module land :-)

Long time coming, but we have arrived!

A few stray modules outside the lineup or other misc bits might still need updates (server facade maybe, for instance), but close enough!
