### ISSUE TITLE
Light & Shadow - Implement art assets

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2575]
### Description

Light & Shadow (L&S) is one of Terasology's major gameplay modules - a CTF PvE gamemode that has red and black chess pieces waging war against each other in a quirky, Alice in Wonderland-inspired setting, with the player being an independent swashbuckling chesspiece that can choose to join one of the factions or operate independently.

![world map](http://forum.terasology.org/attachments/map-png.1021/)

Bringing the L&S word to life requires a large number of assets, from 3D models for chesspiece NPCs to interior decorations and custom cardsy trees. Due to the nature of L&S, these are generally fairly simple in terms of polygon counts and technical difficulty, but still flavourful and fun to implement 🙂 

#### Blocks and Decorations
- [ ] Floor decorations - https://github.com/Terasology/LightAndShadow/issues/19
- [ ] Tao symbol textures - https://github.com/Terasology/LightAndShadow/issues/20
- [ ] Tao symbol 3D model - https://github.com/Terasology/LightAndShadow/issues/21
- [ ] McGuffin, the "F" in CTF - https://github.com/Terasology/LightAndShadow/issues/22
- [ ] Tower turrets - https://github.com/Terasology/LightAndShadow/issues/45
- [ ] Catapult ammo - https://github.com/Terasology/LightAndShadow/issues/38

#### Custom trees and flora
- [ ] Poker Chip tree - https://github.com/Terasology/LightAndShadow/issues/9
- [ ] Backgammon tree - https://github.com/Terasology/LightAndShadow/issues/15
- [ ] Card Crag tree - https://github.com/Terasology/LightAndShadow/issues/16
- [ ] Billiard Bluff tree - https://github.com/Terasology/LightAndShadow/issues/17
- [ ] Domino Piece tree - https://github.com/Terasology/LightAndShadow/issues/18
- [ ] Miscellaneous flora (card suit flowers) - https://github.com/Terasology/LightAndShadow/issues/11
- [ ] Generic "gray" flora - https://github.com/Terasology/LightAndShadow/issues/43

#### NPCs
- [ ] Player Avatar - https://github.com/Terasology/LightAndShadow/issues/48
- [ ] Red Bishop - https://github.com/Terasology/LightAndShadow/issues/37
- [ ] Black Bishop - https://github.com/Terasology/LightAndShadow/issues/36
- [ ] Red Fool (yep, that's a custom piece!) - https://github.com/Terasology/LightAndShadow/issues/30
- [ ] Black Fool - https://github.com/Terasology/LightAndShadow/issues/35
- [ ] Red Rook - https://github.com/Terasology/LightAndShadow/issues/28
- [ ] Black Rook - https://github.com/Terasology/LightAndShadow/issues/32
- [ ] Red Queen - https://github.com/Terasology/LightAndShadow/issues/27
- [ ] Black Queen - https://github.com/Terasology/LightAndShadow/issues/34
- [ ] Red King - https://github.com/Terasology/LightAndShadow/issues/29
- [ ] Black King - https://github.com/Terasology/LightAndShadow/issues/33

### Required skills

- For 2D assets: basic pixel art and texturing skills.
- For 3D assets: intermediate 3D modeling and animation skills. Terasology currently supports .md5 or Wavefront .obj models - a Blender importer is also available.

### Where to start?

- Most of the art assets have concept art available at
http://forum.terasology.org/threads/las-light-and-shadow-art-discussion.762/. Some might even be partially complete - check the relevant issue or ask on IRC to see if that's the case!
