### ISSUE TITLE
Finalize outstanding behavior tree issues for a v2.0.0 merge to develop

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3143]
_Edit: remaining issues covered on a [roadmap card in Trello](https://trello.com/c/OfK8P8Xy) - assistance to flesh out some of the ideas to concrete issues would be appreciated_

Creating this issue to finish out anything remaining for the new behavior tree system as part of releasing v2.0.0 with it live in the near future. So calling this a Blocker for v2.0.0, but with the possibility that we call it ready even with no changes - but in that case I still need some buy-in :-)

State after GSOC finished is that the new system is functional, and affected modules have associated PRs awaiting merges. However @flo brought up some usability concerns toward the end of GSOC that I'd like for us to review and sort out before the merge. However - Slack archives only go so far and at this point I don't have the details handy :-)

Other related stuff (some based on the GSOC project board https://github.com/orgs/Terasology/projects/7):

- [x] The main PR merging v2 into develop: #3138 (also lists a bunch of associated module PRs)
- [ ] #2468 - issue with thread safety, but it may relate to the old system and be obsolete?
- [x] #2232 - a couple outstanding issues after we did some BT prep before GSOC started. Still valid? The  L&S creatures are moving again with the latest PRs (see the [GSOC blog](https://dkambersky.github.io/tera/2017/08/24/google-summer-of-code-2017-final-report.html))
- [ ] Review and submit issues from the project board that should be future todos rather than needed by the time we merge - https://github.com/orgs/Terasology/projects/7
- [ ] Updated examples / doc / tutorial - is https://github.com/Terasology/Behaviors/wiki sufficient? At least a couple pages are incomplete. Make a separate streamlined Tutorial repo and leave reference docs in the Behaviors wiki? Eventually move some of that to the doc site / tutorial trail system.
- [ ] Sample test using http://forum.terasology.org/threads/moduletestingenvironment-integration-testing-with-in-process-engine-objects.1884/
- [ ] Do we need to consider http://forum.terasology.org/threads/flexiblemovement-and-flexiblepathfinding.1902 in the context of the new BT system? Especially since there is at least one known bug related to pathfinding as-is
- [x] Update the mating behavior from WildAnimalsGenome to no longer need AdvancedBehaviors (which will no longer work) - 
- [ ] Consider possible architecture to bring back easy behavior modifications via components (see write-up below + comments at https://github.com/MovingBlocks/Terasology/pull/3138#issuecomment-364870062)

Also for reference the original GSOC issue which also has some lists of stuff: #2070 + @dkambersky's final GSOC blog entry https://dkambersky.github.io/tera/2017/08/24/google-summer-of-code-2017-final-report.html

Assigning this to @dkambersky @flo and @oniatus for reference and hopeful feedback. I suspect @kaen and @nihal111 might also be interested.

**Comment by kaen** [comment]
>  Do we need to consider http://forum.terasology.org/threads/flexiblemovement-and-flexiblepathfinding.1902 in the context of the new BT system? Especially since there is at least one known bug related to pathfinding as-is

I'm happy to maintain the minimal set of working behaviors needed for testing. I don't think it's worth blocking the release since nothing uses FPF in practice.

I think the mini tasks for A/B testing the two behavior systems is useful and properly scoped for GCI :+1:

**Comment by Cervator** [comment]
The big merge is now done - see https://github.com/MovingBlocks/Terasology/pull/3138#issuecomment-364816964 for details :-)

AdvancedBehaviors is the main outstanding point and *I think* related to the genesis of this issue.

@kaen if you want to take a look at latest + FPF I'd be thrilled to hear some sort of update. Can we shove it into the module lineup yet? :D

**Comment by Cervator** [comment]
Some more feedback at https://github.com/MovingBlocks/Terasology/pull/3138#issuecomment-364870062 linking to https://dkambersky.github.io/tera/2017/07/07/on-responsiveness.html in particular: 

AdvancedBehaviors popped up as mostly a workaround for shortcomings in the old system, now addressed in the new. But we still need to update existing things (deer in Lost and some more in WildAnimalsGenome?) to use the new approach.

The one lost thing I believe is being able to affect behavior simply by adding a component to a creature's prefab. Coming up with a better alternative for that in the new system (using a lookup node to load specific predefined trees?) is still on the todo list to finish out this issue.

**Comment by Cervator** [comment]
Beyond https://github.com/MovingBlocks/Terasology/pull/3138#issuecomment-364870062 we just had a bit of chat on Slack and to not lose it (again, at least until the non-profit Slack perk activates) here's a summary of the architectural challenge (not related to the updating of behavior mid-tree which is no longer an issue):

## Challenge

WildAnimalsGenome (WAG) has a `mate.behavior` which unsurprisingly handles the behavior of two animals mating. Pre-v2 engine and behavior tree (BT) overhaul this relied on AdvancedBehaviors (AB) and fully replaced the entire active BT with the mate tree as needed

In the new system the whole tree is considered every tick, so there's no need to replace the tree conditionally. However, that leaves us with the base `critter.behavior` from Behaviors, the base BT of `deer.prefab` in WildAnimals (WA) , as well as the new `mate.behavior` we want to get involved when WAG is enabled. How do we deal with that?

## Short term

There really isn't much to `critter.behavior` in the first place - flee if in trouble, otherwise idly stray around. So the easier solution is to simply replace it with a new slightly more involved BT like a `matingCritter.behavior` that has the flee, stray, AND mating nodes (maybe even just using a tree lookup for the existing `mate.behavior` - but unsure)

Possible remaining question there is how to change the logic in `AnimalMatingAuthoritySystem` from WAG. A new conditional node in the tree should probably use some of the "mating possible?" logic and the tree replacement should be tossed out, replaced with either the `mate.behavior` directly into the new tree or use a lookup

## Long term

As noted previously it would be really nice to be able to do super simple additions of behavior by just adding a component of some sort, maybe even an empty one, to a prefab. That's what AB was really nice for, using weights to try and pick between several added options.

Something similar could be done in the new system, as noted on chat: "could we have some sort of component-interrogating node that checks to see if some `ExtendedBehaviorsComponent` (EBC) is attached to the entity, and if so use conditions + trees in that component to look up and jump to another tree?"

That would easily allow a fix for the current AB/WAG conundrum: simply attach an EBC to the deer via delta in WAG, with details on looking up `mate.behavior` if `x` + add such a component-interrogating node to `critter.behavior`

But for anything beyond the simplicity of adding one alternative new actions to `critter.behavior` (flee if hurt, do `x` if defined, otherwise stray) this gets complicated.

Imagine a more complicated creature: a predator that hunts for food when hungry, mates if able, and migrates according to seasons. Do we fletch all those behaviors into a single tree, which kinda makes sense and would likely look sensible? Or should some of those be optional and only active if a given module is enabled?

If putting it all together piece by peace you *could* use an approach like the EBC and just throw enough logic in there to weigh each option against the others. If the Seasons module isn't enabled then seasonal migration just doesn't get added. But you lose out on some of the clarity of having a pretty tree to look at.

Maybe we need a combination approach: create some checkpoint BTs at differing levels of complexity. `critter.behavior` from the base Behaviors module, which supports the EBC in case somebody wants to add mating via component. Then `matingPredator.behavior` from a MatingPredator module that depends on Mating and Predation, but also has an EBC hook so if somebody enables Migration (which depends on Seasons) then the seasonal migration behavior can be added in via simply adding one additional component.

**Comment by Cervator** [comment]
Closing this with some items addressed and on-going examination of the `ExtendedBehaviorsComponent` possibility by @Naman-sopho over in the GSOC 2018 Oreon project. There's also a [Trello Roadmap Card](https://trello.com/c/OfK8P8Xy) to help cover some future improvements that could need some additional consideration before making further issues.

Thanks again to @dkambersky, @oniatus, @kaen, and everybody else involved in this topic :-)
