### ISSUE TITLE
Follow-ups for create game overhaul

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3400]
In response to #3399 being merged. While testing and checking it out I noticed a few issues we should address:

- [x] Some old code hasn't been deleted yet, such as `CreateGameScreen` (a replacement `NewGameScreen` took over but the old class still exists)
- [x] Some minor changes were made while the create game ovehaul topic branch was pending, for instance there was a module checkbox filter reset button added. I guess maybe another class duplication where the change is in the old copy but needs to be in the new one?
- [x] We might want to add a couple disclaimers: 1) That multi-world isn't done and only the finally selected world will actually be available; 2) That there may be a lengthy loading period after you continue from the module screen
- [ ] ~Ideally we'd add a progress bar / loading page thing instead of letting the game UI freeze while continuing~ - moved to #3585
- [ ] ~Maybe a general review of how the game details screen by @ar0ne and the new work by @TheFlash98 gets along. I know the game details has a "main" box for a world, maybe with the merge it could list the name given to the world like "Perlin-1" ? There won't be multiple worlds to list yet, but soon!™️~  - moved to #3583
- [x] Maybe any sort of branch updating elsewhere, like if @ar0ne or @iaronaraujo need to update pending work for the new screens (will also poke in #ui on Slack)
- [x] Add a second row of buttons to be more consistent with "Select Game"
- [x] Standardize which buttons go where and on what pages, add extras where sensible. For instance add a "Cancel" button from "New Game" onward that will bring the user immediately back to the front of the main menu
- [x] Improve vertical space on the "Advanced Game Setup" screen. It is getting a little tight with the second row of buttons. Maybe shrink the vertical margins in places? Maybe move "Seed" into the same line as its value box? Maybe shorten the warning label so it only takes one line? Less margin above the "Terasology" header title or even skip it entirely past the main menu? It isn't on "Select Game" for instance
  * Yeah probably just remove the Terasology logo from the entirely of the create game flow. Maybe also host/join game. It might be OK on settings pages. I tried to cut out some of the blocks with `"image": "engine:terasology",` in it but that seems to have screwed up some screens completely
- [x] Align the buttons outside the frame with the bottom of the window so they don't move around depending on the height of the main function frame?
- [x] Using the direct-to-play button on module selection screen doesn't activate the selected module (probably doesn't trigger the environment reload at all - if not easily fixable maybe that button should also be deactivated for now until fixed)
- [x] The multiplayer popup about changing your name can occur in some places that aren't multiplayer related
- [x] The convenience skip of the game selection screen when there are no local save games has gone missing again when going _back_ from create game to the main menu (drops you on the empty selection page)
- [ ] ~If you start preparing an advanced game then add a particular world (for instance Pathfinder Testworld, which is rather distinct) then later go quick-start a game the desired world may not be resetting. I ended up in the pathfinder world when trying to play MasterOfOreon, which i think should prefer Perlin, or at the very least reset away from the pathfinder world? In case that's overriding some default. In other words it seems like that setting isn't reset when you start over.~ - moved to #3586
- [x] On Game Details maybe move the dynamic description box over to the bottom right? There's often extra vertical space over there, and two separate scrollable frames would have more vertical space so share there than the two cramped ones in the lower left. Could then probably also enlarge the screenshot slightly (so it can fill up all horizontal space) and maybe put the general info block on top of it?
- [x] Maybe we should make the default state of module filters be everything unchecked? Right now starting with some of them on leaves you with a relatively small list even with a ton of modules present

**Comment by ar0ne** [comment]
Hey @TheFlash98, 
JFYI, Got NPE when try to "Configure" new world with "Island World" generator (PolyWorld module should be active).

**Comment by Cervator** [comment]
Another potential suggestion that just came to mind: Should we include "Play now" buttons on some of the pages in the _middle_ so to say? If you just want to enable some modules but accept whatever default world generator you don't really need to go through each additional screen.

The phases should still happen, but the user input part could be skipped.

**Comment by iaronaraujo** [comment]
I've done some refactoring in the SelectGameScreen to remove the duplications from it, RecordScreen and ReplayScreen.
https://github.com/MovingBlocks/Terasology/pull/3376/commits/665825b3dd7e483f27d326d627788a8823c7e28e

**Comment by Cervator** [comment]
@iaronaraujo go ahead and stick it in a PR sometime instead, easier :-) If you haven't already and I just missed it :D

Follow-up idea: The "Select Game" screen has 4 active buttons plus a "Back" button in a second row. I forgot where it came up but if you then click "Create" the "New Game" screen has the "Back" button first in a single row of 3 buttons (lined up with where "Create" was on the previous screen). If you go further you get "Back"/"Continue" buttons.

On some pages that purely have "Back"/"Continue" maybe just having those two in one row in the same order each time would make sense. But I like the idea of a second row with a grander impact on flow. And we could probably use a quick "Play" button on screens like "Advanced Game Setup" that then finish the flow with any remaining choices set to default, as well as a big "Cancel" button that gets you entirely out of the new game flow rather than having to hit back several times.

Maybe we can add the new buttons and use two rows to see if that results in better overall UX?

**Comment by Cervator** [comment]
Bump - merged one set of tweaks, more needed, updated initial issue description with checkboxes and more items :-)

**Comment by Cervator** [comment]
Bumping after merging #3426 - that checked off a few things and made me think of a few more. Also found one regression (a skip selection bug is back)

**Comment by iaronaraujo** [comment]
I noticed that when creating a new game the game title is always "null" unless you create the game through the "advanced" steps.

**Comment by Cervator** [comment]
@iaronaraujo 

> I noticed that when creating a new game the game title is always "null" unless you create the game through the "advanced" steps.

Try out latest develop now with #3451 merged - we might be able to confirm that one as fixed :-)

I encountered a new case, I think:

* Start after deleting `config.cfg` or in one case I had just picked MasterOfOreon from quick start giving me its default Perlin world
* Go back to create game, select BuilderSampleGameplay (making it change the default world to BSG)
* Select MasterOfOreon again and quickstart - my expectation would be I'd get Perlin again
* Spawn in a void as oddly the BSG world seemed to still be picked, even though the module wasn't even active (got errors in the log about not being able to find some stuff - but I *did* spawn somehow!)

Not totally sure if that's legit or my workspace but if anybody else could try to replicate I'd appreciate it.

Oddly if I picked Light & Shadow (which has a default of the simple L&S world) the default world gen from starting via quick start *did* correctly change.

**Comment by Cervator** [comment]
Update - have been thinking more about some ideas on how to clarify the overall process. Here's a proposed mockup with three variants. The first two use the side margins to essentially show a list of screens to come (or screens you've passed) while the third just reworks the buttons at the bottom. I'm not really sure what would look nicer or fit better so it will likely take some experimenting.

![creategameuimockup](https://user-images.githubusercontent.com/1063833/48971445-c7995a00-efe7-11e8-8075-cef1ff444d5d.png)

If we have the space I'd love to see the first option dynamically list all related previous and future pages, including having each option count as a jump button to proceed to that page. In some cases there may be hard prerequisites you have to complete first in which case affected page-buttons should be grayed out.

**Comment by AndyTechGuy** [comment]
Hey all! I'm doing the GCI task to improve the presentation for the create game UI.

To see what works best, I'm starting by making samples of button position based on the suggestions above:

- This is based almost entirely off the second mockup, with the buttons on the side with disconnected labels. I found that in this screen, it was very difficult to fit the three columns and the two buttons on the side together, so I shifted the center of the screen to display on two columns instead of one.
![advancedgamesetup](https://user-images.githubusercontent.com/44126397/49192492-d3717d00-f355-11e8-919d-39c6e5d60387.PNG)

- This is a mixture of the second and third mockups, with buttons on the side, but the label inside the button instead of the outside. This one is my personal favorite; it's simple but effective.
![universesetup](https://user-images.githubusercontent.com/44126397/49192896-a8882880-f357-11e8-844c-9dcbcf914226.PNG)

- This is based entirely off the third mockup (it is even the same screen), with buttons on the bottom with the label inside the button. I think having the buttons on the bottom makes it easier to stay within the margins, avoiding problems like in the first sample.
![worldpregeneration](https://user-images.githubusercontent.com/44126397/49193173-b9856980-f358-11e8-86c7-946ad454a603.PNG)

- This is a mixture of the second and third mockups that reverses the second one, with buttons on the bottom but the label outside the button instead. Because this screen is the last screen in the process, only the first button has labels, since there is nothing to label on the second button. I think this causes a strange imbalance in the screen, with the left button looking very dense, and the right button looking very light. 
![spawnpreview](https://user-images.githubusercontent.com/44126397/49193508-e0906b00-f359-11e8-8f2c-36ab999cd2f4.PNG)

I didn't make any samples based off the first mockup; I'm worried that having the four options on the side on the first screen may cause the screen to become more cluttered. However, I do like the idea of having non-linear game creation, maybe instead we could have the main screen be the core of the creation, with buttons simply containing links to the other screens (Module Selection, Universe Setup, Pre-Generation, Preview, Spawn Select), and buttons to play/return? Lots of ideas to potentially play with here :)

These are some ways I have been thinking about how to change the screen flow, any ideas/opinions on which route to go?

The repo that I have been working on for the samples can be found [here](https://github.com/AndyTechGuy/Terasology/tree/advancedCreateTests)

**Comment by Cervator** [comment]
Thanks for the latest round of fixes @AndyTechGuy and everybody else that have been involved in moving these issues forward. With almost all of them addressed I've split out a final few to their own issues and am closing this as done :-)
