### ISSUE TITLE
Roadmap for replace Pathfinding with FlexiblePathfinding

### ISSUE THREAD

**Issue by DarkWeird** [MovingBlocks/Terasology#4981]
### Motivation

* High memory usage of Pathfinding(especially in java)
* Unnecessary PF's NavGraph usage (e.g. CoreGameplay don't needs it, but NavGraph is creates)
* We have alternative already (FPF)

### Concerns

* Is there specific expertise that will be needed for this effort?
* Does this effort have dependencies on other efforts?
* Do you expect this effort to conflict with any other efforts?
* What are potential drawbacks of the effort?
* What are maintenance or continuous efforts that will persist beyond the completion of this effort?

### Task Breakdown

- [x] Extract pathfinding behaviours from behaviours (this was done in https://github.com/Terasology/FlexibleMovement and https://github.com/Terasology/PathfindingBehaviors ) 
- [x] Rewrite dependency from behaviours to PF's behaviours for depending modules (most specified dependencies were unused)
- [x] Write PF's behavours alternatives for FlexableMovement.
- [x] Replaces PF behavours with FPF behaviours in depending modules (we actually did a near in-place migration in Terasology/Behaviors#88 and Terasology/Behaviors#89. therefore, we did not need to change much in modules. all relevant PRs are linked in those two PRs)
- [x]  Replace PF with FPF in omega lineup (https://github.com/Terasology/Index/commit/9e0b097850d9f0490fff0c55ea894a11d375d097 and https://github.com/Terasology/Index/commit/3ceb298733bfee39d843a6d8eca14492ba059a9d)
- [x] Follow-ups from Terasology/Behaviors#89
    - [X] check if use of `@In` possible
      ```
      @In
      private WorldProvider world;
      ```
      - it's not possible in behavior actions
    - [x]  use initialization in `construct()` consistently throughout behavior actions - https://github.com/Terasology/Behaviors/pull/102
      ```
      @Override
      public void construct(Actor actor) {
          if (world == null) {
              world = CoreRegistry.get(WorldProvider.class);
          }
      }
      ``` 
      - this will work if @In has no effect, i.e., the field is initialized to null
      - this will work if @In is fixed and initializes the field correctly, making the code in construct a no-op
      - we preserve the information that we want to use @In in actions 
    - [X] ~~formatting of assets (JSON)~~
      - behaviors cannot be properly JSON-formatted without changing the behavior parser
    - [X] formatting of Java files 
    - [x] removing dead and commented code (or revive if necessary) - https://github.com/Terasology/Behaviors/pull/103
      - no dead / commented code in `assets`
      - [`FlexibleMovementDebugLayout`](https://github.com/Terasology/Behaviors/blob/develop/src/main/java/org/terasology/module/behaviors/debug/FlexibleMovementDebugLayout.java) almost entirely commented out
      - [`ValidatePath`](https://github.com/Terasology/Behaviors/blob/develop/src/main/java/org/terasology/module/behaviors/actions/ValidatePath.java) action has some out-commented code
    - [X] ~~assess and iterate naming of actions and behaviors~~
      - this is a potential rabbit-hole and more or less endless task... should be tracked separately and specified in more detail
    - [x] slim down test assets (`testcharacter.prefab` itself, duplicates in children of parent character prefabs) Terasology/Behaviors#90
    - [x] revert replacement of behavior node prefabs for findPathTo, moveAlongPath and moveTo https://github.com/Terasology/Behaviors/pull/91

**Optional tasks and improvements**

- Move code and features from Gooyes Defence to FlexableMoving.
- Provide documentation for FPF.
-

**Comment by skaldarnar** [comment]
We went for a more ... straight ahead path now by integrating what was already done for https://github.com/Terasology/FlexibleMovement back into https://github.com/Terasology/Behaviors.

- https://github.com/Terasology/Behaviors#88
- https://github.com/Terasology/Behaviors#89

GooeyDefence already uses FlexiblePathfinding directly, so I guess that step is not required, but might be a good test for the new behaviors.

**Comment by skaldarnar** [comment]
**Update:** Current state of the migration (with a couple of local changes I'll need to push later when back home) I can start the game again, although there are still failing tests and some worrying log messages and non-optimal behavior of mobs, e.g., with WildAnimals.

- 4 failing Behaviors tests
	```
    MovementTests. [walking, leaping]: leap
    MovementTests. [swimming]: leap
    MovementTests. [swimming]: diagonal
    MovementTests. [swimming]: straight
	```

- injection `@In` not working for behavior actions
	```
    18:40:23.697 [main] WARN  o.t.engine.registry.InjectionHelper - SetTargetToNearbyBlockNode wanted PluginSystem injected but CoreRegistry has none.
    18:40:23.697 [main] WARN  o.t.engine.registry.InjectionHelper - MoveToAction wanted WorldProvider injected but CoreRegistry has none.
    ...
    18:40:23.769 [main] WARN  o.t.engine.registry.InjectionHelper - FindPathToNode wanted PathfinderSystem injected but CoreRegistry has none.
	```

- broken prefabs?
	```
    18:40:23.698 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'WildAnimals:babyDeer' contains unknown component 'StrayIfIdle'
    18:40:23.505 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'Behaviors:jobBuildBlock' contains unknown component 'Work
	```

- broken behavior trees or behavior actions? (IllegalArgumentException is silently swallowed... o.O)
	```
    18:52:40.472 [main] WARN  o.t.e.physics.bullet.BulletPhysics - Can't update Trigger entity with a non-finite position/rotation?! Entity: EntityRef{id = 3169, netId = 0, prefab = 'WildAnimals:sheep'}

    18:11:07.457 [Test worker] DEBUG org.terasology.engine.core.ComponentSystemManager - Initialising org.terasology.engine.logic.behavior.BehaviorSystem@2ffebb03
    18:11:07.460 [Test worker] ERROR org.terasology.engine.core.ComponentSystemManager - Failed to initialise system org.terasology.engine.logic.behavior.BehaviorSystem@2ffebb03
    java.lang.IllegalArgumentException: Unknown behavior node type setup_continuous_pathfinding

    18:11:07.466 [Test worker] DEBUG org.terasology.engine.core.ComponentSystemManager - Initialising org.terasology.engine.logic.behavior.CollectiveBehaviorSystem@c892b6
    18:11:07.466 [Test worker] ERROR org.terasology.engine.core.ComponentSystemManager - Failed to initialise system org.terasology.engine.logic.behavior.CollectiveBehaviorSystem@c892b6
    java.lang.IllegalArgumentException: Unknown behavior node type setup_continuous_pathfinding
	```

**Comment by jdrueckert** [comment]
>     * broken prefabs?
>       ```
>        18:40:23.698 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'WildAnimals:babyDeer' contains unknown component 'StrayIfIdle'
>        18:40:23.505 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'Behaviors:jobBuildBlock' contains unknown component 'Work
>       ```

https://github.com/Terasology/WildAnimals/pull/93 addresses the first of the two.

**Comment by jdrueckert** [comment]
>     * broken behavior trees or behavior actions? (IllegalArgumentException is silently swallowed... o.O)
>       ```
>        18:52:40.472 [main] WARN  o.t.e.physics.bullet.BulletPhysics - Can't update Trigger entity with a non-finite position/rotation?! Entity: EntityRef{id = 3169, netId = 0, prefab = 'WildAnimals:sheep'}
>       
>        18:11:07.457 [Test worker] DEBUG org.terasology.engine.core.ComponentSystemManager - Initialising org.terasology.engine.logic.behavior.BehaviorSystem@2ffebb03
>        18:11:07.460 [Test worker] ERROR org.terasology.engine.core.ComponentSystemManager - Failed to initialise system org.terasology.engine.logic.behavior.BehaviorSystem@2ffebb03
>        java.lang.IllegalArgumentException: Unknown behavior node type setup_continuous_pathfinding
>       
>        18:11:07.466 [Test worker] DEBUG org.terasology.engine.core.ComponentSystemManager - Initialising org.terasology.engine.logic.behavior.CollectiveBehaviorSystem@c892b6
>        18:11:07.466 [Test worker] ERROR org.terasology.engine.core.ComponentSystemManager - Failed to initialise system org.terasology.engine.logic.behavior.CollectiveBehaviorSystem@c892b6
>        java.lang.IllegalArgumentException: Unknown behavior node type setup_continuous_pathfinding
>       ```

This is due to `setup_continuous_pathfinding` being removed in https://github.com/Terasology/Behaviors/pull/89.

**Comment by skaldarnar** [comment]
I think with merging Terasology/Behaviors#89 and related PRs we're done with the main list of tasks as described in this issue. I'll copy over the respective follow-ups from that issue description such that we can keep track of it here (will update the initial issue).

**Comment by jdrueckert** [comment]
Regarding the lacking support for dependency injection in behavior actions, I noticed, that we do have _something_ in that direction in [BehaviorTreeBuilder::addAction](https://github.com/MovingBlocks/Terasology/blob/v5.2.0/engine/src/main/java/org/terasology/engine/logic/behavior/core/BehaviorTreeBuilder.java#L213).
However, I don't know whether - and if not why - this is sufficient.

I wonder whether this might be related to the respective fields not being registered, yet, rather than the dependency injection not working as expected...?

If we are sure that the fields are registered and the dependency injection is implemented incorrectly, https://github.com/MovingBlocks/Terasology/issues/5003 might be related.

**Comment by jdrueckert** [comment]
All documented follow-ups done, closing this issue.
