### ISSUE TITLE
Snapshot Pre-Revive Status

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/Terasology#5104]
### Motivation

* We are on the verge of severely cutting down and rebuilding our codebase aiming to revive Terasology
* At some point in the future we might want to have a look at the state before this revive effort
* We need some way to identify the pre-revive commit in engine, modules, and TeraNUI to be able to find that state again

### Proposal

* Add a "pre-2023-revive" tag to engine, omega module, TeraNUI, and JNLua repos
* Definition of Done:
  * Engine repo, TeraNUI repo, JNLua repo, and all omega module repos have "pre-revive" tag

### Considered Alternatives

* [On Discord](https://discord.com/channels/270264625419911192/1125053027448012862), I suggested to copy repos/orgs as the pre-revive snapshot
* [On Discord](https://discord.com/channels/270264625419911192/1125053027448012862/1125066947936133181), @skaldarnar suggested to make a final build, and upload artifacts including the respective compilers and JREs for archiving purposes
* [On Discord](https://discord.com/channels/270264625419911192/1125053027448012862/1125066655261790278), @skaldarnar suggested to sync https://github.com/Nanoware/Terasology with the current state we want to preserve

### Concerns

* Tagging all 100+ omega module repos manually will be tedious, we should consider automating this

### Task Breakdown

* [x] Add "pre-2023-revive" tag to engine repo
	* [x] https://github.com/MovingBlocks/Terasology/tree/legacy-pre-2023-revive 	
* [x] Add "pre-2023-revive" tag to every omega module repo
* [x] Add "pre-2023-revive" tag to TeraNUI repo
* [x] Add "pre-2023-revive" tag to JNLua repo 

### Additional Notes

* @skaldarnar [mentioned](https://discord.com/channels/270264625419911192/1125053027448012862/1125089237369356318) that his `gooey-node` tool might help with the module tagging

**Comment by skaldarnar** [comment]
Workspace lock-file as generated by https://github.com/skaldarnar/node-gooey using 

```sh
gooey workspace pin --exact
```

<details>
<summary>workspace-lock.json</summary>

```json
{
  "name": "Terasology",
  "version": "5.4.0-SNAPSHOT",
  "ref": "4c177c68b141a990381eabeddbba5fb7c884fecb",
  "lockfileVersion": 1,
  "modules": {
    "modules/AdditionalFruits": {
      "name": "AdditionalFruits",
      "version": "1.1.0-SNAPSHOT",
      "ref": "1bce2103f8760a8a61815e513aa1b29628b0d8a7"
    },
    "modules/AdditionalItemPipes": {
      "name": "AdditionalItemPipes",
      "version": "1.1.0-SNAPSHOT",
      "ref": "2db193e81e558159d903174db43db30e26d706cd"
    },
    "modules/AdditionalRails": {
      "name": "AdditionalRails",
      "version": "1.1.0-SNAPSHOT",
      "ref": "5ed9df627b0e9cdd73cab819f6083e0331549be4"
    },
    "modules/AdditionalVegetables": {
      "name": "AdditionalVegetables",
      "version": "1.1.0-SNAPSHOT",
      "ref": "65a2b23a876e6a3f6223c7abf28d4829e6065192"
    },
    "modules/AdvancedRails": {
      "name": "AdvancedRails",
      "version": "1.1.0-SNAPSHOT",
      "ref": "0b0793c43011a60fbedb73a96977de240dc582ef"
    },
    "modules/AdventureAssets": {
      "name": "AdventureAssets",
      "version": "1.1.0-SNAPSHOT",
      "ref": "415dbe8a82bfc8592d610472657a266574888f57"
    },
    "modules/Alchemy": {
      "name": "Alchemy",
      "version": "1.3.0-SNAPSHOT",
      "ref": "f91b292f067ab25f12721f9e33915d03c7a585fb"
    },
    "modules/AlchemyPlantGenerator": {
      "name": "AlchemyPlantGenerator",
      "version": "1.0.0-SNAPSHOT",
      "ref": "cbc54adbf7fcdd260f2b1314684d26074c5f83b2"
    },
    "modules/AlterationEffects": {
      "name": "AlterationEffects",
      "version": "1.2.0-SNAPSHOT",
      "ref": "d61f03a7b90ee423d67e395205842c4ef708da29"
    },
    "modules/Anatomy": {
      "name": "Anatomy",
      "version": "1.1.0-SNAPSHOT",
      "ref": "63200f5f0697599e3797a1a681f2d09475f9ed13"
    },
    "modules/AnotherWorld": {
      "name": "AnotherWorld",
      "version": "1.1.0-SNAPSHOT",
      "ref": "36175fb46a7f772dc3c174b29cc6a3df4821cfd6"
    },
    "modules/AnotherWorldPlants": {
      "name": "AnotherWorldPlants",
      "version": "1.1.0-SNAPSHOT",
      "ref": "caa20b3f6795df5c3cb6312b8cecd31b1990973f"
    },
    "modules/Apiculture": {
      "name": "Apiculture",
      "version": "1.1.0-SNAPSHOT",
      "ref": "c438de082de1a5bc27f88862881ad1b6348ab724"
    },
    "modules/BasicCrafting": {
      "name": "BasicCrafting",
      "version": "1.1.0-SNAPSHOT",
      "ref": "88ff60ec129287c356abca505d7250989cc977b4"
    },
    "modules/Behaviors": {
      "name": "Behaviors",
      "version": "1.1.1-SNAPSHOT",
      "ref": "b07ceb5e6878c46ab8186632e2447d7ea11373a4"
    },
    "modules/BiomesAPI": {
      "name": "BiomesAPI",
      "version": "4.1.1-SNAPSHOT",
      "ref": "d5283a8fa69757c692c142fe4761f621da97a327"
    },
    "modules/BlockDetector": {
      "name": "BlockDetector",
      "version": "1.4.0-SNAPSHOT",
      "ref": "54ac9351cbfa2fdbc311a700ec8dd7b62de17a71"
    },
    "modules/BlockNetwork": {
      "name": "BlockNetwork",
      "version": "1.1.0-SNAPSHOT",
      "ref": "17320dad05df31fc1623a33bcff36ed03491dc41"
    },
    "modules/BlockPicker": {
      "name": "BlockPicker",
      "version": "1.2.0-SNAPSHOT",
      "ref": "85a69070f2bd507926a69c5eea194cf02d4436d7"
    },
    "modules/Books": {
      "name": "Books",
      "version": "1.2.0-SNAPSHOT",
      "ref": "009f9e3910614e55ca73918cbdcaebe43b659a73"
    },
    "modules/Breathing": {
      "name": "Breathing",
      "version": "1.1.0-SNAPSHOT",
      "ref": "6040d5d10eb712968a487c38bf51cdba8582fd3c"
    },
    "modules/CakeLie": {
      "name": "CakeLie",
      "version": "1.1.0-SNAPSHOT",
      "ref": "922de27967f3368f78f2a72bb81379ed4198a7e9"
    },
    "modules/Caves": {
      "name": "Caves",
      "version": "1.2.0-SNAPSHOT",
      "ref": "88b6a7e438305fcc050d5c6d9c5d6fe6dfc33621"
    },
    "modules/ChangingBlocks": {
      "name": "ChangingBlocks",
      "version": "1.1.1-SNAPSHOT",
      "ref": "f81c8a1d5a455a6c37002920d5f405a45e57e795"
    },
    "modules/CheatsForAll": {
      "name": "CheatsForAll",
      "version": "1.1.0-SNAPSHOT",
      "ref": "93d631bd9b2d9a6a80fe340d8a8eef896ef9543c"
    },
    "modules/ChiselBlocks": {
      "name": "ChiselBlocks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "fd965bd2eca2017c334fe6818cadc167dc6d214e"
    },
    "modules/ChrisVolume1OST": {
      "name": "ChrisVolume1OST",
      "version": "1.1.0-SNAPSHOT",
      "ref": "630bb91755718d5d378a38c6badd794f637ea04a"
    },
    "modules/ChrisVolume2OST": {
      "name": "ChrisVolume2OST",
      "version": "1.1.0-SNAPSHOT",
      "ref": "a4d55c06a45398ef042b09d919d9e77974c2f425"
    },
    "modules/Cities": {
      "name": "Cities",
      "version": "1.2.0-SNAPSHOT",
      "ref": "8a6b0a90a9bd6134750c79bf20043b9341d1b732"
    },
    "modules/ClimateConditions": {
      "name": "ClimateConditions",
      "version": "1.0.1-SNAPSHOT",
      "ref": "a7f0c60bf39ddbe27e58736efae1ec7a45aacdda"
    },
    "modules/Climbables": {
      "name": "Climbables",
      "version": "1.1.0-SNAPSHOT",
      "ref": "4a5500beed1f04b9771faacf6e0ff3a31bbc3baf"
    },
    "modules/CombatSystem": {
      "name": "CombatSystem",
      "version": "1.1.0-SNAPSHOT",
      "ref": "85c39e22471e5c600a48fc3b9c3b4a5098e57a49"
    },
    "modules/CommonWorld": {
      "name": "CommonWorld",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7dc6a86db56fc1e148378765db62135c10516033"
    },
    "modules/Compass": {
      "name": "Compass",
      "version": "1.1.0-SNAPSHOT",
      "ref": "11985d9ec8475af4526e702aac6227b593d04466"
    },
    "modules/ComputerMonitors": {
      "name": "ComputerMonitors",
      "version": "1.1.1-SNAPSHOT",
      "ref": "c82609b7837ac4aa2f2e81100139d7b2f62a8c73"
    },
    "modules/Cooking": {
      "name": "Cooking",
      "version": "1.2.0-SNAPSHOT",
      "ref": "fd727f3775353a6ecf87db1de539d898b47fc67c"
    },
    "modules/CoreAdvancedAssets": {
      "name": "CoreAdvancedAssets",
      "version": "1.3.0-SNAPSHOT",
      "ref": "56daaab55e356ca168327ac4753a8326075ccb99"
    },
    "modules/CoreAssets": {
      "name": "CoreAssets",
      "version": "2.3.0-SNAPSHOT",
      "ref": "77898ffc35f3cf2d366412aeeb1b405fbf0326c1"
    },
    "modules/CoreRendering": {
      "name": "CoreRendering",
      "version": "1.1.2-SNAPSHOT",
      "ref": "32df29598caf562674bd05eb2349aaad747e0f63"
    },
    "modules/CoreSampleGameplay": {
      "name": "CoreSampleGameplay",
      "version": "4.1.1-SNAPSHOT",
      "ref": "176903b10748c4e40cbedd10022094c08e552574"
    },
    "modules/CoreWorlds": {
      "name": "CoreWorlds",
      "version": "2.1.0-SNAPSHOT",
      "ref": "33eea24b630c1f0957bf1573138dff986510b401"
    },
    "modules/CustomOreGen": {
      "name": "CustomOreGen",
      "version": "1.1.0-SNAPSHOT",
      "ref": "66d252eb2f127b93d17cb97d6e4594483c9af703"
    },
    "modules/DamagingBlocks": {
      "name": "DamagingBlocks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "abe23b308ac60fbe6a6192ac930210dc18fa9a58"
    },
    "modules/Dialogs": {
      "name": "Dialogs",
      "version": "1.1.0-SNAPSHOT",
      "ref": "d510447014510f49480cc060a344737fba162c78"
    },
    "modules/Drops": {
      "name": "Drops",
      "version": "1.2.0-SNAPSHOT",
      "ref": "4352c75b60a77751c807fda57f54cb2788cb778c"
    },
    "modules/Durability": {
      "name": "Durability",
      "version": "1.2.0-SNAPSHOT",
      "ref": "b9afc5701f81d5c5a46fda3215156fa5ed930793"
    },
    "modules/DynamicCities": {
      "name": "DynamicCities",
      "version": "1.1.0-SNAPSHOT",
      "ref": "82c579876c804e205d305ab888cd1e2ff1b4cb9b"
    },
    "modules/Economy": {
      "name": "Economy",
      "version": "1.2.0-SNAPSHOT",
      "ref": "ceadb44ccff9136504a5de26652aee0a7b32f207"
    },
    "modules/EdibleFlora": {
      "name": "EdibleFlora",
      "version": "1.1.0-SNAPSHOT",
      "ref": "3fb585a285dd1eb175816ff5cbbece8739f55ca9"
    },
    "modules/EdibleSubstance": {
      "name": "EdibleSubstance",
      "version": "1.1.0-SNAPSHOT",
      "ref": "85a65ac27b1d54d2af30f87fbebc3f798b55eeb9"
    },
    "modules/Equipment": {
      "name": "Equipment",
      "version": "1.3.0-SNAPSHOT",
      "ref": "243d8d36a1d8375920422c0510558bd9ca7e362f"
    },
    "modules/EquipmentSmithing": {
      "name": "EquipmentSmithing",
      "version": "1.2.0-SNAPSHOT",
      "ref": "80e7cbee63f557234d3f31f868460fcad49d6747"
    },
    "modules/EventualSkills": {
      "name": "EventualSkills",
      "version": "1.1.0-SNAPSHOT",
      "ref": "371bcb822771d4574fae0e107fcf68c49c3b5f10"
    },
    "modules/Exoplanet": {
      "name": "Exoplanet",
      "version": "1.0.0-SNAPSHOT",
      "ref": "0ba5d3e7c4ca8d431f9cc6ed6db34da55fec05af"
    },
    "modules/Explosives": {
      "name": "Explosives",
      "version": "1.1.1-SNAPSHOT",
      "ref": "541fb168010726b6a16b89376b54c602103b8a97"
    },
    "modules/FallingBlocks": {
      "name": "FallingBlocks",
      "version": "1.3.0-SNAPSHOT",
      "ref": "89ea765d647b6af8c1d5c83e2309e1db870eaba1"
    },
    "modules/Fences": {
      "name": "Fences",
      "version": "1.1.0-SNAPSHOT",
      "ref": "a98fa52c804aefe9a3be55b2bc862b13aba79ad6"
    },
    "modules/FlexiblePathfinding": {
      "name": "FlexiblePathfinding",
      "version": "1.1.0-SNAPSHOT",
      "ref": "8842aaaf5570dbb2e3b72079b85c9b04e4c8ef12"
    },
    "modules/FlowingLiquids": {
      "name": "FlowingLiquids",
      "version": "1.4.0-SNAPSHOT",
      "ref": "419e6c7f0a56797a82e4b8dd0db4f72248c5c1db"
    },
    "modules/Fluid": {
      "name": "Fluid",
      "version": "2.1.0-SNAPSHOT",
      "ref": "3b580fad9165ccef75d5127dbab7b80e26c708c1"
    },
    "modules/FluidComputerIntegration": {
      "name": "FluidComputerIntegration",
      "version": "1.1.0-SNAPSHOT",
      "ref": "2298b7147d6a513dae6e4355df52ea6ae0a1d6ab"
    },
    "modules/FlyingIslands": {
      "name": "FlyingIslands",
      "version": "1.1.1-SNAPSHOT",
      "ref": "9eafb459840a75441103634db47f7ee1bb431e3f"
    },
    "modules/FunnyBlocks": {
      "name": "FunnyBlocks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "ce7dda7643812ac149dda4273b4e1fc76b736b82"
    },
    "modules/Furnishings": {
      "name": "Furnishings",
      "version": "1.1.1-SNAPSHOT",
      "ref": "3069462cffe76d3238f5ccaec9160ddab5f94966"
    },
    "modules/GenericRocks": {
      "name": "GenericRocks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "b0dcea0c3367af7f590fadffb88c06addf4b5a42"
    },
    "modules/Genome": {
      "name": "Genome",
      "version": "1.0.1-SNAPSHOT",
      "ref": "c0146ad4b349bc2fb8ca0cee7af6ad2362b727f6"
    },
    "modules/Gooey": {
      "name": "Gooey",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7ad6112c513d39f043ff3993309afb9bce37afda"
    },
    "modules/GooeyDefence": {
      "name": "GooeyDefence",
      "version": "1.1.1-SNAPSHOT",
      "ref": "09e166879344c8a8f1a4e4502d99a060c20ddd47"
    },
    "modules/GooeysQuests": {
      "name": "GooeysQuests",
      "version": "1.1.2-SNAPSHOT",
      "ref": "38e68c0731057790f3a86bd040aeb0dd40b5c826"
    },
    "modules/GrowingFlora": {
      "name": "GrowingFlora",
      "version": "1.1.0-SNAPSHOT",
      "ref": "4735fa2a7daeb9267f17d2712c94409101d9e511"
    },
    "modules/Health": {
      "name": "Health",
      "version": "2.0.0-SNAPSHOT",
      "ref": "335d6d730c0a46d0bdd95dcadc39adaa263634ad"
    },
    "modules/HjerlHede": {
      "name": "HjerlHede",
      "version": "1.2.0-SNAPSHOT",
      "ref": "f78a355eb2c60b6a0c46ee9c96e4e3daced6961b"
    },
    "modules/HumanoidCharacters": {
      "name": "HumanoidCharacters",
      "version": "1.1.0-SNAPSHOT",
      "ref": "1b193fdae2b7c8faf2934af3fa1aa543445f3fb4"
    },
    "modules/Hunger": {
      "name": "Hunger",
      "version": "1.2.0-SNAPSHOT",
      "ref": "beb2e4aa52b8206366dd28f68f942a386c755554"
    },
    "modules/IRLCorp": {
      "name": "IRLCorp",
      "version": "1.3.0-SNAPSHOT",
      "ref": "a872c7de361812df08005adbb9f47a698c4dde42"
    },
    "modules/InGameHelp": {
      "name": "InGameHelp",
      "version": "1.2.0-SNAPSHOT",
      "ref": "3be1f506e905089aecb2cd35bb22b77447078faa"
    },
    "modules/InGameHelpAPI": {
      "name": "InGameHelpAPI",
      "version": "1.1.0-SNAPSHOT",
      "ref": "465e9fe78806ee4a9f4f0f71adc1b501cda57c66"
    },
    "modules/Inferno": {
      "name": "Inferno",
      "version": "1.0.0-SNAPSHOT",
      "ref": "5cca810eaeb19dbacf3d4b694f4859a312266ad1"
    },
    "modules/Inventory": {
      "name": "Inventory",
      "version": "1.5.0-SNAPSHOT",
      "ref": "979c2469201567d53951f6e3bfcfa3d1f18ba666"
    },
    "modules/ItemPipes": {
      "name": "ItemPipes",
      "version": "1.1.0-SNAPSHOT",
      "ref": "511cd8f37fa0e5f381540362ebf67b3119f23aff"
    },
    "modules/ItemRendering": {
      "name": "ItemRendering",
      "version": "1.2.0-SNAPSHOT",
      "ref": "8735faab8a76a709dc1fe8ce4b1ff6747735cac8"
    },
    "modules/JoshariasSurvival": {
      "name": "JoshariasSurvival",
      "version": "1.1.0-SNAPSHOT",
      "ref": "59263219672ade1455e9361180317920304c2fd3"
    },
    "modules/Journal": {
      "name": "Journal",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7d777df392aeffe3103caac1b8ff48e3a6a27ea3"
    },
    "modules/KComputers": {
      "name": "KComputers",
      "version": "1.1.1-SNAPSHOT",
      "ref": "23c3d3d3876ce3ed9f166734c05962efe139a60b"
    },
    "modules/Kallisti": {
      "name": "Kallisti",
      "version": "1.1.0-SNAPSHOT",
      "ref": "15e04d42f03350e8bbc0fe82cb71f9816e73a67b"
    },
    "modules/Lakes": {
      "name": "Lakes",
      "version": "2.0.0-SNAPSHOT",
      "ref": "ab0185513c818e69e6a4a700d71b8f101997a8fb"
    },
    "modules/LegacyMusic": {
      "name": "LegacyMusic",
      "version": "1.1.0-SNAPSHOT",
      "ref": "f114e82c28e15d4b282d2a0a2a03bd5d3461e570"
    },
    "modules/LightAndShadow": {
      "name": "LightAndShadow",
      "version": "1.2.0-SNAPSHOT",
      "ref": "c9b3bcafd4894442b74a9d7bca096a508ae66510"
    },
    "modules/LightAndShadowResources": {
      "name": "LightAndShadowResources",
      "version": "1.2.0-SNAPSHOT",
      "ref": "d9bac21348c3d8874e242855e0c51b17f06ed874"
    },
    "modules/Lost": {
      "name": "Lost",
      "version": "1.1.0-SNAPSHOT",
      "ref": "65505ea1c3a568fbc3c69c8e1639f9113ba0b580"
    },
    "modules/Machines": {
      "name": "Machines",
      "version": "1.3.1-SNAPSHOT",
      "ref": "79031ebcc9b1a6418b2487a87fc8f1331ea78fc8"
    },
    "modules/ManualLabor": {
      "name": "ManualLabor",
      "version": "1.4.0-SNAPSHOT",
      "ref": "c301ddf5d9735504cd96d7bc49da594aa2fd67f7"
    },
    "modules/ManualLaborEventualSkills": {
      "name": "ManualLaborEventualSkills",
      "version": "1.1.0-SNAPSHOT",
      "ref": "febc4631e168fd65ad2949b54e06703ffc37ce81"
    },
    "modules/MarkovChains": {
      "name": "MarkovChains",
      "version": "1.6.1-SNAPSHOT",
      "ref": "5a2fbe8642da411585a827a4e88d2605446d9cf4"
    },
    "modules/MasterOfOreon": {
      "name": "MasterOfOreon",
      "version": "1.1.0-SNAPSHOT",
      "ref": "30985551fef506c957f214f5f15c1765e205923b"
    },
    "modules/Maze": {
      "name": "Maze",
      "version": "1.1.0-SNAPSHOT",
      "ref": "209a61c4add9ccbd43e87e76e20413a5c45ae3f3"
    },
    "modules/MedievalCities": {
      "name": "MedievalCities",
      "version": "1.1.0-SNAPSHOT",
      "ref": "61136594e849bde34015df9561e04668e1e29269"
    },
    "modules/MetalRenegades": {
      "name": "MetalRenegades",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7cc5cfc04fbb174427d80403d713d174ce683da4"
    },
    "modules/Minerals": {
      "name": "Minerals",
      "version": "1.0.0-SNAPSHOT",
      "ref": "e3650d9e07aa07c35af99eb60141a7a7ef2cc742"
    },
    "modules/Minesweeper": {
      "name": "MineSweeper",
      "version": "1.0.0-SNAPSHOT",
      "ref": "e2c8af338db185c1509e901208245b48e0616d8a"
    },
    "modules/Minimap": {
      "name": "Minimap",
      "version": "1.1.0-SNAPSHOT",
      "ref": "ae9eccba7cc62cb35d13bfb9cad937c5ff98d44e"
    },
    "modules/MobileBlocks": {
      "name": "MobileBlocks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "2451eaef5192195c4e38c7cefe5b995a6c084974"
    },
    "modules/ModularComputers": {
      "name": "ModularComputers",
      "version": "1.1.0-SNAPSHOT",
      "ref": "99c8c7bbfdc3158078f5aa10b39d30f166a046ac"
    },
    "modules/ModuleTestingEnvironment": {
      "name": "ModuleTestingEnvironment",
      "version": "0.3.3-SNAPSHOT",
      "ref": "adf9b6df0407a62c15092a82960d8711e28bb7b7"
    },
    "modules/MoreLights": {
      "name": "MoreLights",
      "version": "1.1.0-SNAPSHOT",
      "ref": "47e4b2b05f9066c83c2d28d0a467fe96c5f5ac0d"
    },
    "modules/MultiBlock": {
      "name": "MultiBlock",
      "version": "1.1.1-SNAPSHOT",
      "ref": "760cc7280d4482445f074a055132a775a8a67b5a"
    },
    "modules/MusicDirector": {
      "name": "MusicDirector",
      "version": "1.1.0-SNAPSHOT",
      "ref": "b46a7edc296d590598bc32c6a7d654ba97a82877"
    },
    "modules/NameGenerator": {
      "name": "NameGenerator",
      "version": "1.1.0-SNAPSHOT",
      "ref": "026d3cc01b3bb22661bd153d79fdb5a2db78c5f9"
    },
    "modules/Notifications": {
      "name": "Notifications",
      "version": "0.2.0-SNAPSHOT",
      "ref": "c77b54c7719bab1b29c551bc28323af788bf87fc"
    },
    "modules/OreGeneration": {
      "name": "OreGeneration",
      "version": "2.1.0-SNAPSHOT",
      "ref": "4f6c174fb14d5846e8a0a75966ea7a386626ffa6"
    },
    "modules/Oreons": {
      "name": "Oreons",
      "version": "1.1.0-SNAPSHOT",
      "ref": "298f483f8cc27f63fa9619138f0e655eb2d3308e"
    },
    "modules/ParadIce": {
      "name": "ParadIce",
      "version": "0.1.0-SNAPSHOT",
      "ref": "3f8343e90ae16cf7b5f395ea023809d93dfaa72c"
    },
    "modules/PhysicalStats": {
      "name": "PhysicalStats",
      "version": "1.1.0-SNAPSHOT",
      "ref": "de087a2d2c97e5ea9643123049bec33f0964901c"
    },
    "modules/PlantPack": {
      "name": "PlantPack",
      "version": "1.2.2-SNAPSHOT",
      "ref": "bf65f3a32a83b783fa582d3f49e8ce85e9531632"
    },
    "modules/PolyWorld": {
      "name": "PolyWorld",
      "version": "1.1.0-SNAPSHOT",
      "ref": "52dbef90b76cc8e15bc252160ce7b387d9b6a475"
    },
    "modules/Portals": {
      "name": "Portals",
      "version": "1.1.0-SNAPSHOT",
      "ref": "d7415c8eb435caf50dcea6a520d25f4ad69b064e"
    },
    "modules/PotentialEnergyDevices": {
      "name": "PotentialEnergyDevices",
      "version": "1.2.0-SNAPSHOT",
      "ref": "9380a2d71e45a1a08b0b0d9ead6745ca20b94b0d"
    },
    "modules/Potions": {
      "name": "Potions",
      "version": "1.4.0-SNAPSHOT",
      "ref": "25312fbca31c75f507d8adf36a2e384c27c15ed1"
    },
    "modules/Projectile": {
      "name": "Projectile",
      "version": "1.2.1-SNAPSHOT",
      "ref": "c44e99cad4b1d89e96c6a7343220d1ec0febc523"
    },
    "modules/Rails": {
      "name": "Rails",
      "version": "1.1.0-SNAPSHOT",
      "ref": "85e62b4fe25fb4f124d0eaf115a5fe3b10dcfc50"
    },
    "modules/Sample": {
      "name": "Sample",
      "version": "1.1.0-SNAPSHOT",
      "ref": "68e1729fe91a0631c25e40c82197ae9645a876fc"
    },
    "modules/Scenario": {
      "name": "Scenario",
      "version": "1.1.0-SNAPSHOT",
      "ref": "47b83f1d7fac1ddff6c98b552bab715b431631e5"
    },
    "modules/Seasons": {
      "name": "Seasons",
      "version": "1.1.0-SNAPSHOT",
      "ref": "4744a208d157e6fae3e2a8ba8074b645f0031b0e"
    },
    "modules/SegmentedPaths": {
      "name": "SegmentedPaths",
      "version": "1.1.0-SNAPSHOT",
      "ref": "06398b180f375b16e6bf0e3b1e4c257973b058b0"
    },
    "modules/Sensors": {
      "name": "Sensors",
      "version": "1.1.0-SNAPSHOT",
      "ref": "da644ad5d44d3df88ef3b57d4ec003d69dffce5e"
    },
    "modules/ShatteredPlanes": {
      "name": "ShatteredPlanes",
      "version": "1.0.0-SNAPSHOT",
      "ref": "d710bc3f5b7d4286c56c6fef11a38ddccbe8ca45"
    },
    "modules/Signalling": {
      "name": "Signalling",
      "version": "1.1.0-SNAPSHOT",
      "ref": "34a34be87783c8be228178bac67cbaf895380b85"
    },
    "modules/SimpleFarming": {
      "name": "SimpleFarming",
      "version": "2.2.0-SNAPSHOT",
      "ref": "baacd757720069eb9246b8d0b449e98d8cdbcc37"
    },
    "modules/Smithing": {
      "name": "Smithing",
      "version": "1.2.0-SNAPSHOT",
      "ref": "cbf03bd36d49a1ed3fbd7932f726943f6d899d11"
    },
    "modules/Soils": {
      "name": "Soils",
      "version": "1.1.0-SNAPSHOT",
      "ref": "3fa521285a122df49e9057616d5b04b84c6760f9"
    },
    "modules/SoundyGenetics": {
      "name": "SoundyGenetics",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7e8563a8d03977ccba2c1a31589d8a881b6e7457"
    },
    "modules/Spawning": {
      "name": "Spawning",
      "version": "1.1.0-SNAPSHOT",
      "ref": "169d4e695ba7edbbd5260e5244eccbaeb5e17a74"
    },
    "modules/StaticCities": {
      "name": "StaticCities",
      "version": "1.1.0-SNAPSHOT",
      "ref": "94a82941dd83fb10851cb0e29f7f3b8c79be78f8"
    },
    "modules/StructuralResources": {
      "name": "StructuralResources",
      "version": "2.3.0-SNAPSHOT",
      "ref": "913595d1a22018c4841b7c2143c0fa7e81a083ce"
    },
    "modules/StructureTemplates": {
      "name": "StructureTemplates",
      "version": "1.1.0-SNAPSHOT",
      "ref": "7446a49e4e9db5bd911a058f6321c6567c9f2b61"
    },
    "modules/SubstanceMatters": {
      "name": "SubstanceMatters",
      "version": "2.1.0-SNAPSHOT",
      "ref": "77f4c07d7efb7a7528a3239e121948d24c01dd84"
    },
    "modules/Tasks": {
      "name": "Tasks",
      "version": "1.1.0-SNAPSHOT",
      "ref": "3e5347b88d09ec833467d1b330a5bd9b0672cab7"
    },
    "modules/Thirst": {
      "name": "Thirst",
      "version": "1.1.0-SNAPSHOT",
      "ref": "2480f923efd1a02fb95fa06a2d8e89e57cfa97d4"
    },
    "modules/Valentines": {
      "name": "Valentines",
      "version": "1.1.0-SNAPSHOT",
      "ref": "b1f4f14db51961066756321f42c185fa84af2bb4"
    },
    "modules/WeatherManager": {
      "name": "WeatherManager",
      "version": "1.0.0-SNAPSHOT",
      "ref": "7867014d141b4cac803d662f7ba24d93fa64b491"
    },
    "modules/WildAnimals": {
      "name": "WildAnimals",
      "version": "1.1.0-SNAPSHOT",
      "ref": "93eaf7622a1076015642bb1c6150a066dab43c65"
    },
    "modules/WildAnimalsGenome": {
      "name": "WildAnimalsGenome",
      "version": "1.1.0-SNAPSHOT",
      "ref": "834c3808094a3e849652573bf5a4450c1c714d71"
    },
    "modules/Workstation": {
      "name": "Workstation",
      "version": "1.2.0-SNAPSHOT",
      "ref": "da9ce88bac92a0ed1e77c554d63d897077afe04d"
    },
    "modules/WorkstationCrafting": {
      "name": "WorkstationCrafting",
      "version": "2.1.0-SNAPSHOT",
      "ref": "13d254667f795805fba132b6a2dca8fe78537169"
    },
    "modules/WorkstationInGameHelp": {
      "name": "WorkstationInGameHelp",
      "version": "1.1.0-SNAPSHOT",
      "ref": "20a2d60d0cd22c526ed6cdb6b251799b4cf01900"
    },
    "modules/WorldlyTooltip": {
      "name": "WorldlyTooltip",
      "version": "1.3.0-SNAPSHOT",
      "ref": "afb680f1d57f8add5cf7dc9f1ad5593c40f6108f"
    },
    "modules/WorldlyTooltipAPI": {
      "name": "WorldlyTooltipAPI",
      "version": "1.1.0-SNAPSHOT",
      "ref": "fc0f727c8c470e6caac7dccd9c511b29a6b45f48"
    },
    "modules/Xmas": {
      "name": "Xmas",
      "version": "0.1.0-SNAPSHOT",
      "ref": "d494a779724a28add875471f81c38b47d1d1d776"
    }
  },
  "libs": {
    "libs/JNLua": {
      "name": "JNLua",
      "version": "",
      "ref": "93e12fa10d226d35bcbc7a93b3b0d8e272c1d213"
    },
    "libs/TeraNUI": {
      "name": "TeraNUI",
      "version": "",
      "ref": "95491a5952d53bc796008528e62387a51450b093"
    }
  }
}

```

</details>

**Comment by skaldarnar** [comment]
I think all tag creations went through, executed with the following little script:

```sh
# in Terasology workspace root with Omega modules and libs checked out locally

echo 'Mark the last commit before the 2023 "Revive" activity

We hope for a more active period for Terasology again, possibly including
drastic cuts of code, major rewrites, and other disruptive activities.

On 2023-07-02, the following repositories were marked with this tag:
- the engine repository MovingBlock/Terasology
- 148 modules of the "Omega lineup" in Terasology/*
- two libraries, MovingBlocks/TeraNUI and MovingBlocks/JNLua' > msg.txt

for repo in . $(find libs/ modules/ -type d -depth 1); do
  git -C $repo tag -a pre-2023-revive -F $(pwd)/msg.txt
  git -C $repo push origin pre-2023-revive
done
``` 

The 148 modules belonging to the Omega distro are taken from https://github.com/Terasology/Index/blob/c6efdcde48fac27f3c2f4573b5d0e945ec5abaf8/distros/omega/gradle.properties.

You can verify 
- the engine tag at https://github.com/MovingBlocks/Terasology/releases/tag/pre-2023-revive,
- tags for the libraries TeraNUI at https://github.com/MovingBlocks/TeraNUI/releases/tag/pre-2023-revive and JNLua at https://github.com/MovingBlocks/JNLua/releases/tag/pre-2023-revive
- tags for modules on the respective releases/tags pages, for instance, Health at https://github.com/Terasology/Health/releases/tag/pre-2023-revive

**Comment by jdrueckert** [comment]
Closed as complete. If we decide that tagging is not sufficient, we can reopen it again with further action items.

**Comment by skaldarnar** [comment]
Also created a dedicated branch `legacy-pre-2023-revive` with the pre-revive state: https://github.com/MovingBlocks/Terasology/tree/legacy-pre-2023-revive

**Comment by jdrueckert** [comment]
Today I also tagged and branched-off for https://github.com/MovingBlocks/CrashReporter and https://github.com/MovingBlocks/SplashScreen

**Comment by jdrueckert** [comment]
... and https://github.com/MovingBlocks/JNBullet
